using System;
using System.Collections.Generic;
using System.Reflection.Metadata.Ecma335;

namespace uiExp.Shared
{
    public class LoadFeedConvos
    {
        public static List<PublicConvo> ConvoList = new List<PublicConvo>();

        private static string[] lines6 { get; } =
            {
                "Marshall Sloane:",
                "Majoritarian politics commanding the morals is what trump is about rejecting",
                "It’s a righteous mission if he weren’t a racist buffoon ",
                "Eli Burnes:",
                "hmmm",
                "Marshall Sloane:",
                "The tea party is just tired of majoritarian tyranny ",
                "I’ve been saying this for a while",
                "Eli Burnes:",
                "Who is the majority",
                "Marshall Sloane:",
                "The woke",
                "Who command industry and schools",
                "Eli Burnes:",
                "But the woke are a minority",
                "Marshall Sloane:",
                "And government ",
                "Eli Burnes:",
                "With power",
                "Marshall Sloane:",
                "But they are a majority of noise",
                "Eli Burnes:",
                "true",
                "That’s the irony",
                "Marshall Sloane:",
                "They command press, schools, and industry ",
                "We live in a society governed by majoritarian tyranny of the woke",
                "It troubles me often",
                "Eli Burnes:",
                "hah",
                "Insane how ever corporation made a statement on BLM",
                "Marshall Sloane:",
                "Yup",
                "Eli Burnes:",
                "Radical politics is establishment politics",
                "Marshall Sloane:",
                "Yes and no",
                "Eli Burnes:",
                "Status quo",
                "Marshall Sloane:",
                "It’s not radical it’s very tame ",
                "Eli Burnes:",
                "That’s the point",
                "*my point",
                "Marshall Sloane:",
                "French Revolution, libya, Egypt, China",
                "Those were radical ",
                "Ours is so tame",
                "Marching, rioting ",
                "Isn’t wild",
                "It’s childish",
                "Eli Burnes:",
                "yep",
                "Marshall Sloane:",
                "There is no radical reforming of ideas",
                "No robust idea on a reformulation of society besides vomiting up washed up socialist speak that has never worked",
                "Eli Burnes:",
                "Isn’t that the history of antiracism though, like blacks just want to be treated like whites",
                "Marshall Sloane:",
                "But they are",
                "By and large",
                "Eli Burnes:",
                "So it doesn’t require radical rethinking to suceed",
                "That’s fiar",
                "But discrepancies are still absurd wrt poverty, incarceration, crime etc.",
                "Police are a straw man in all of this perhaps",
                "A scapegoat",
                "Marshall Sloane:",
                "That’s the issue. Our majoritarian politics validates their stance, but nothing changes. Wealth and class don’t change. Their criminality doesn’t change. So they’re just overwhelmed by this lethargic creep towards our countries eventual realization that nothing can be done besides their effort to fall into American conformism until they flourish too. ",
                "I wonder when that day will come.",
                "Marshall Sloane:",
                "Because, the feature left out is that in order to be treated as a white you in fact need to act like oneZ",
                "That may sound heinous ",
                "But it’s the functioning of American societt",
                "Eli Burnes:",
                "Hm that makes sense interesting interpretation, so success in america requires conformism on your view",
                "Marshall Sloane:",
                "Entirely",
                "It’s how we operate",
                "Eli Burnes:",
                "Asian Americans, are they conformist?",
                "Marshall Sloane:",
                "We are a conformist society",
                "Yes",
                "Entirely",
                "Eli Burnes:",
                "But they do it to an extreme",
                "Marshall Sloane:",
                "But it’s conformism to an idea. That’s why there is such anxiety between immigrants and natives, right? If each immigrant class strives to do better, then the prior class will stagnate and be left behind - fueling this cycle of anxiety.",
                "Eli Burnes:",
                "Hm",
                "Marshall Sloane:",
                "Blacks got the worst of the stick. They - like many whites - are left behind. But they didn’t have the class and wealth to still rise up.",
               "Like some WASPS are still rich. It isn’t just more recent immigrants",
                "Because class is still currency here.",
                "Eli Burnes:",
                "true.",
                "Wasp society is decadent though",
                "Dying and fracturing",
                "Marshall Sloane:",
                "I suppose",
                "We live in a society where clout govern",
                "And without their clout they’re imploding and resorting to normal means of achieving clout",
                "Which is flashing money",
                "Eli Burnes:",
                "haha",
                "The culture of the nouveau riche is taking over. Because “class” as a state of mind and manners is less and less respected",
                "Simpler and more vulgar ways are being used to assert dominance and prestige",
                "Marshall Sloane:",
                "Yes",
            };



        private static string[] lines1 { get; } =
        {
                "Eli Burnes:",
                "\"They stalk about in our midst as living reproaches, as warnings to us—as though health, fitness, strength, pride, the sensation of power, were really vicious things in themselves, for which one would have some day to do penance, bitter penance. Oh, how they themselves are ready in their hearts to exact penance, how they thirst after being hangmen! (GM III 14)\"",
                "Here Nietzsche describes the revolt of the lowly, the oppressed, against the strong",
                "He thinks the less powerful have succeed by making the powerful guilty – guilty for their power",
                "The psychological trick of of the oppressed, on Nietzsche’s view, is to make the attributes of the powerful seem ridiculous, cause for guilt",
                "Can we compare this to modern notions of privilege?",
                "Kush Sharma:",
                "Creating guilt among the powerful functions in a fractal way. The aristocrats of the Roman republic had the same internal dynamics - e.g. Gaius Marius, a low-born but extremely competent military general who denounced the high aristocracy of his day for responding to crises with haughty arrogance that didn't correspond to their abilities. They had power, but competence isn't hereditary like power is/was, so the critiques hit on a legitimate point.",
                "Eli Burnes:",
                "What do you mean by fractal?",
                "Kush Sharma:",
                "Just like the bottom of the bottom (e.g. Jesus and the Jews) were able to critique one level up - establishment Jewish rabbis + the Roman administrators, the same dynamics were occurring within the highest reaches (and maybe occur in every local class / power conflict?)",
                "Eli Burnes:",
                "Hmm interesting",
                "Kush Sharma:",
                "Interesting comparison to upper middle class vs global elite, white lower class vs black / brown underclass?",
                "Elites seem to be failing - globalization didn't live up to its promises, at least for those who already lived in wealthy Western countries. Technology is stagnating. There are legit critiques of competence, but maybe easier to dress those critiques up in moral terms - BLM, privilege, wokeness?",
                "Eli Burnes:",
                "Yeah. To your last text–people see themselves in the context of their local hierarchies. for everyone, there’s always a more powerful group and a less powerful group. There’s research that suggests people compare their incomes to those around them. to someone in the upper middle class the excessive wealth of the elite elite might invoke jealousy + condemnation.",
                "Moral/psychological memes are perhaps the most effective way for the powerless to gain power/challenge those in power. Nietzsche totally understands this",
                "Kush Sharma:",
                "Ahhh yes, and that means that whoever is one level up in the apparent hierarchy becomes the",
                "*oops more to come",
                "\"enemy\" and all levels above that are illegible to the person at a particular local level. One explanation for why the Trump demo's anger has been aimed at those one below (illegal immigrants, POC lower / under class) and one above (liberal academics, professional / managerial class); and that anger was leveraged by right elites.",
                "Does the dominance of a moral / psych meme imply that it is more truthful or moral? Or does it just imply greater memetic fitness?",
                "Eli Burnes:",
                "Ohh interesting take on trump. Certainly true that his anti elite rhetoric does not target the rich + most powerful in the way that Warren’s did in her primary campaign. she has a different audience",
                "The wokeism meme (which is quite complex, of course) may not be that fit–it might just fizzle out. But by definition it’s been super high fitness up to this point",
                "Don’t think dominance implies truth",
                "But it does suggest that it fit’s nicely into previously established belief systems/memeplexes",
                "For instance wokeism thrives on the generally accepted idea (in Western European liberalism) that equality is the most important moral standard/ideal",
                "And the basic equality of humans the fundamental moral fact",
                "Moral/psych memes have to seem true, at least",
                "my view is that morality is socially constructed (to some extent) so being dominant means participating in constructing morality at least",
                "Kush Sharma:",
                "Yep! The fitness of wokeism is super interesting - my take is that it's not fit, because it misunderstood the basic nature of power in a capitalist system. Power in the US doesn't come from political activism, protests, or governmental bodies; all the areas where wokeness has gained some power. All those are subservient to capital or irrelevant int he face of capital - see wokeism being coopted by F500s and rejected by entrepreneurs. Ofc future forecasts are always hand wavy though :)",
                "Ya, and it hit trouble when it contradicted another deeply held moral fact - freedom of speech and expression (esp in the US)",
                "Being a part of the dominant morality gives you cultural capital - interesting dynamics occur when (mainstream) cultural capital is less and less valuable",
                "Eli Burnes:",
                "Yes wokeism seems to me to be not that effective in terms of real political gains for black people–massive investment in poor, black, urban areas, for instance, is badly needed but nowhere in sight. We’ll see if the police reforms we get are actually effective and fair or are not...",
                "Freedom of speech and expression might not be the biggest roadblock to wokeism– it runs up against humanism, to some extent we should see people first as human beings and only second as people of a certain race. It also feels christian. There’s heresy, apostates, original sin (slavery). Not sure if this is good for fitness or not–we live in a secular culture but puritanism is still quite dominant. Any resistance movement meets backlash, gains for black people in the US seem always to be met with pushback from whites. Maybe wokeism will succeed because it changes what type of push back is acceptable. wokeism undermines the foundation of white power by making white people question their privilege–often to an insane degree. ",
                "Kush Sharma:",
                "Yeah! It's post-Christianity Christianity, but without Salvation! It fills ~80% of the gap Christianity left in the culture, but without offering metaphysics or \"ultimate\" morality - it only offers relative, \"profane\" social morality. It's redistributionist rather than growth-oriented.",
                "Yep I think that's fair and it will succeed in making gains for black people, but at the expense of cultural progress as a whole. MLK-style civil rights didn't have this drawback, and even Malcolm X-style secession didn't as much - one focused on unity, not guilt, and the other focused on internal strength and exit, not voice",
                "Difficult to say if progress (for black people) is possible without the guilt though - a huge part of the guilt is baked into the social reality of the last 200y, and needs to be confronted and processed by the culture",
                "Eli Burnes:",
                "good point on salvation. By definition, psychological purification from white supremacy (a sort of salvation or redemption) is not possible. And the apparent goal of the present racial justice movement–exact equity in all social outcomes between whites and blacks–is frankly not possible, unless we get to a world in which race matters not at all. There seems to be no endpoint.",
                "I think white guilt might actually be doing some effective things",
                "Kush Sharma:",
                "Yep - maybe then the question is one of attention allocation between different causes? Social / racial justice is needed, but with 10 other causes that are equally if not more pressing (stagnation, climate change, ex-risk, etc) allocating all our cultural attention to a cause that's inherently zero-sum and profane rather than positive-sum and sacred seems dangerous",
                "Eli Burnes:",
                "Here’s an example. I think that education is the most effective way for wealthy white people to maintain their family’s power–paying for private school may be more effective than a trust fund. Insofar as this is true, wokeism might be working, because it undermines the idea that white people should be able to use money to get better education. Woke white parents are getting uncomfortable maintaining their family’s privilege–their guilt might lead to material and psychological solidarity with non white people.",
                "For sure, attention allocation this summer shifted almost entirely (at least in white managerial class) to racial justice, evidenced by NYT bestsellers. Not sure racial justice get’s too much attention, of course it often hasn’t gotten enough.  But perhaps it wasn’t a good use of attention in the summer leading up to the election.",
                "What can we pay attention to that’s sacred?",
                "Kush Sharma:",
                "Isn't non-zero sum privilege desirable though? If private school is just a grift to help your kid get into Harvard easier (which in many cases it is which is where this is super valid), that's not a great form of privilege. But if private school is a superior education that allows your kid to contribute in a more valuable way to society, then despite the fact that privilege creates privilege, it also creates competence, which should be positive-sum. Then white guilt is actively destructive!",
                "I'd say it's hard to find things that are collectively sacred at the level of Christianity until / if new forms of religion appear, but I think there are things that are more sacred. Elon-esque human expansion across the universe, scientific progress, localism over national / global politics & rebuilding communities, a \"holy war\" against climate change",
                "Eli Burnes:",
                "Oh for sure I agree. Guilt like this about schools can be destructive. Parents are literally denying their kids opportunities because many black people don’t get to have them. The obvious solution is to make the opportunity available to black + white people! racial justice is not necessarily zero sum, but that’s how it’s playing out in the streets and in the pages of the NYT...",
                "^ reply to your first text",
                "I think some of the appeal of racial justice is that it feels sacred",
                "Kush Sharma:",
                "For sure! I do have to run now but this was awesome, had a great time and think we came up with some dope ideas :)",
                "Eli Burnes:",
                "Great talk man"

            };

        private static string[] lines3 { get; } =
        {
                "Caleb Rhodes:",
                "Ok, so today we will be talking about the Philip Guston Retrospective Controversy",
                "Ethan do you want to set the scene",
                "Ethan Fields:",
                "Happy to! So the current controversy around Philip Guston’s work boils down to the fact that a retrospective of his was delayed over the summer as a result of the death of George Floyd and the ensuing protest for racial justice in the US",
                "This was supposed to be a show that spanned a couple of museums in the US and UK, specifically the Houston MFA, Boston MFA, National Gallery of Art, and Tate Modern",
                "Caleb Rhodes:",
                "Yes, the national gallery of art and the 4 partner museums have since rescheduled initially for 2024 and now to 2022. The reason for the delay was because of KKK imagery in Guston’s (a white Jewish man’s) art that the curators claim wasn’t contextualized enough",
                "Ethan Fields:",
                "But it was pushed back to 2024 until recently when it was placed in between at 2022",
                "Great minds think alike!",
                "Caleb Rhodes:",
                "Interestingly, the move has been largely panned across the board by a diverse and well-known crowd of artists and cultural commentators",
                "I guess the first question Ethan is whether you agree that the show should have been postponed?",
                "Ethan Fields:",
                "That’s certainly the million dollar question, and I think one needs to start by examining the intentions of the Museum Board of directors who really pushed the decision.",
                "Caleb Rhodes:",
                "Fair enough",
                "Ethan Fields:",
                "Even prior to the pandemic, the art and museum world was in a state of flux as institutions were critiqued for accepting dubious donations",
                "So the board members clearly wanted to mitigate any sense of controversy that could have exposed them to public dissatisfaction",
                "Caleb Rhodes:",
                "Yeah this is definitely a defensive move, but was it motivated by money or just fear of outrage?",
                "Ethan Fields:",
                "I know that a lot of people found the decision patronizing, and I personally believe that adopts a rather “snowflake” view of the public",
                "Caleb Rhodes:",
                "Absolutely, and from what I’ve read, the exhibition catalogue does a good job of contextualizing these images already",
                "Ethan Fields:",
                "In response to your second question: I’ve been fortunate enough to get some exposure to the Ford Foundation the past several months through my time at the Museum of Chinese in America",
                "And Darren Walker, the head of the foundation, was one of the voices advocating for the postponement",
                "The Ford Foundation is actually a really fantastic source of funding for cultural institutions across the country",
                "And they recently rolled out a generous donation of over $200 million to a variety of small to mid sized institutions across the US to help them survive Covid",
                "Caleb Rhodes:",
                "Interesting! It just seems to me that at a moment of “cultural reckoning,” cultural institutions and their benefactors  should not be shying away from tough conversations but leaning into them",
                "Ethan Fields:",
                "These institutions mostly being cultural museums representing specific ethnic or immigrant stories like MOCA",
                "I completely agree!",
                "This is just to say that I think that some of their intentions likely stemmed from a good place",
                "Caleb Rhodes:",
                "And I believe everyone’s intentions here are good",
                "Ethan Fields:",
                "As cultural institutions, I think museums have a responsibility to shape the public’s sense of morality and tell honest stories",
                "Those stories aren’t always easy",
                "And they can be quite uncomfortable at times",
                "But confronting them is certainly the only way to move forward",
                "Caleb Rhodes:",
                "Yes and I find it disappointing that these museums think they are doing a service by stalling a conversation",
                "Frankly it seems more about them than about the public or the story",
                "Ironically perhaps they are the ones who aren’t ready for a real conversation",
                "Ethan Fields:",
                "Yes they certainly seem scared of rocking the boat in any manner",
                "Caleb Rhodes:",
                "Truly peak self-censorship",
                "Ethan Fields:",
                "But it’s part of the climate given the Warren Kanders debacle at the Whitney",
                "You’re certainly right, and this seems like a big issue these days",
                "People are really scared of overstepping in any way because they’re scared of being cancelled or labeled something negative",
                "And while I certainly believe that hate speech and racism deserves to be curtailed and rooted out, I do think that people make mistakes",
                "And they can make them in good faith",
                "But if we don’t allow people to make mistakes",
                "Then they will never grow from them",
                "And that will just breed another cultural disaster",
                "Caleb Rhodes:",
                "Absolutely! I think we’re stumbling on another convo here. But definitely this controversy is revealing the extent to which our discourse on race is paralyzed by fear of being perceived wrongly",
                "But thanks Ethan, always great to talk! 😘",
                "Ethan Fields:",
                "Yes, that topic deserves a book not a text exchange for sure",
                "Always happy to chat!",
            };

        private static string[] lines5 { get; } =
        {
                "Ian Liefer:",
                "Why do you think Biden is gonna win?",
                "He has unprecedented black and Latino support",
                "And hasn’t lost any of his base",
                "Henry Burnes:",
                "Not true elderly people and suburban women are going for Biden, two critical demographics for Trump",
                "*latino male support",
                "Ian Liefer:",
                "True but it’s unclear if the data supports that in key swing states",
                "Trumps elderly turnout has been strong in Florida",
                "And he has huge Latino support in Arizona and Nevada",
                "Henry Burnes:",
                "Trump can win Florida",
                "As long as Biden wins PA",
                "Ian Liefer:",
                "PA +2 today",
                "Trump",
                "And he registered 80,000 Amish",
                "Henry Burnes:",
                "Wrong",
                "Ian Liefer:",
                "90% pro trump",
                "Henry Burnes:",
                "Wow",
                "Hadn’t heard about that",
                "Might be hard to get to the polls in buggies",
                "Ian Liefer:",
                "True",
                "Henry Burnes:",
                "Trump has no campaign message",
                "Has no idea how to run against Biden",
                "Ian Liefer:",
                "It’s called MAGA bro",
                "Henry Burnes:",
                "He’s getting separate",
                "Ian Liefer:",
                "Lol",
                "I agree",
                "Henry Burnes:",
                "MAGA doesn’t work after you’ve been president for a term",
                "Ian Liefer:",
                "How should he be running then",
                "Henry Burnes:",
                "Pivot on COVID and accept responsibility",
                "Push through a stimulus",
                "Ian Liefer:",
                "Unrelated but I know a kid working in DC for chief economist and he’s a democrat so he’s not biased and he said the democrats won’t accept one before the election",
                "Just strategically",
                "Henry Burnes:",
                "Maybe. But they passed one in the house",
                "Ian Liefer:",
                "True",
                "I agree lol",
                "Henry Burnes:",
                "So does the country descend into chaos if trump wins ?",
                "Ian Liefer:",
                "I’m just disagreeing with everything",
                "I think so",
                "Yeah",
                "Honestly there will prob be conflict either way",
                "Henry Burnes:",
                "Let’s buy some guns then",
                "Ian Liefer:",
                "Agreed",
                "It’s funny how everyone just thinks their party will win"
            };
        private static string[] lines0 { get; } =
        {
                "Eli Burnes:",
                "Dude what do you think of contemporary interior design / architecture. Like the aesthetic of all the new coffee shops",
                "Like incandescent lights, white walls, chalkboard menus, maybe plants",
                "Tunc Otzemir:",
                "I think it’s good for the cafes",
                "Eli Burnes:",
                "How so",
                "It’s kind of nice",
                "Comforting",
                "Tunc Otzemir:",
                "It is nice but not super cozy",
                "Eli Burnes:",
                "cold",
                "Tunc Otzemir:",
                "And promotes an atmosphere in which ppl are prompted to leave in a reasomable time",
                "Which is good for then",
                "But i do like the extremely cozy, home like, never leave kinda places",
                "Eli Burnes:",
                "ah",
                "Me too",
                "Tunc Otzemir:",
                "Esp if u wanna work or sit around and chat",
                "this is like emblematic of the focus on productivity",
                "Eli Burnes:",
                "yes",
                "They are almost designed for a quick business meeting",
                "Tunc Otzemir:",
                "like come get your coffee enjoy a beautiful, therapeutic space for half an hour or so",
                "Eli Burnes:",
                "Or a quick phone call",
                "Tunc Otzemir:",
                "And move on to your actual life or whatever gif",
                "Gig u need to do",
                "Yeah",
                "Eli Burnes:",
                "The lights and the greenery give a sort of fake homey vibe",
                "Tunc Otzemir:",
                "Like i think esp the design of the seated spaces are the most important in determining the longetivity of the stay",
                "Eli Burnes:",
                "hm",
                "Tunc Otzemir:",
                "I think not homey but, fake outdoorsy. So you will feel refreshed",
                "Eli Burnes:",
                "ah",
                "Tunc Otzemir:",
                "Cause the cozy places are usually dark and not soul nurturing",
                "They are like libraries and homes mixture",
                "Eli Burnes:",
                "Why isn’t that soul nurturing",
                "Tunc Otzemir:",
                "I mean it is",
                "But if you’re taking a quick break from work to get coffee or whatever",
                "You need a lot of light",
                "To make u feel like you’re in a park or sth",
                "Eli Burnes:",
                "yep",
                "Tunc Otzemir:",
                "This space is gorgeous tho the one u sent",
                "But most of the times it is implemeted badly",
                "Eli Burnes:",
                "Yeah fair",
                "Tunc Otzemir:",
                "Would you say blue bottle has a similar design?",
                "Eli Burnes:",
                "Like the places in the smith center",
                "Tunc Otzemir:",
                "For example I hate that place",
                "I feel like I am in a factory it’s overcrowded, everyone is uncomfortably seated",
                "Eli Burnes:",
                "Looking through the window is like looking into a fishbowl",
                "An auarium",
                "*aquarium",
                "It has lots of wood and light",
                "Super white",
                "You think the seats make people stay for less time",
                "The spaces feel so professional and overly designed it gives the sense that there’s now way they could mess up your order, that nothing could go wrong",
                "Like a fancy hospital",
                "Tunc Otzemir:",
                "Yeah I agree",
                "It is like a high tech factory",
                "Eli Burnes:",
                "Haha",
                "Tunc Otzemir:",
                "I want my order to have the possibility of being messed up",
                "That means there is actual human care and labor that goes into it",
                "Eli Burnes:",
                "Yes",
                "Tunc Otzemir:",
                "And that there exists a possibility that when it is not messed up",
                "It will be provided with care and love rather then precision",
                "Like u know they're also cutting costs on everything in these kinda of places",

            };
        private static string[] lines2 { get; } =
        {
                "Jasmine Wang:",
                "Hello hello!",
                "Along with ‘what tech calls thinking’ I also ordered xiaowei wang’s A Blockchain Chicken Farm and it covers a lot of relevant themes to what we were talking about earlier this week",
                "Saffron Huang:",
                "ohh i’ve been meaning to read that! what about it is relevant?",
                "Jasmine Wang:",
                "Basically goes into tech x rural China -- the most interesting part was their defense of China’s ‘copycat’ culture was actually incredibly generative + innovative",
                "Saffron Huang:",
                "ohhh that actually kind of has stewart brand esque ‘back-to-the-land’ vibes. like, use tech in isolated community settings?",
                "what kind of stuff did they make",
                "Jasmine Wang:",
                "There are entire supply chains for example that crop up around copying high-ticket products -- not just copying say, Gucci bags, but consumer electronics with cheaper / locally made materials for example",
                "Hmm say more about that? Haven’t read much of Brand’s stuff",
                "Saffron Huang:",
                "if they’re making consumer electronics then maybe its less like brand’s countercultural movement in the 60s",
                "Jasmine Wang:",
                "Just to finish the thought about Blockchain Chicken Farm - this sort of innovation their view is much more democratic, opens up participation + consumption of consumer good and technologies of all sorts to much more of society / across global currency disparities",
                "Saffron Huang:",
                "but the idea is, individual, local use of technology in small communes - a very personalised, cybernetics-based approach to change through small scale tech and bringing people together",
                "ok so its actually more democratic than US innovation?",
                "Jasmine Wang:",
                "Hm! I think this is a bit different yes - Taobao villages (wherein village homes in China are repurposed as small-scale factories) are actually interlinked and integrated with a much bigger supply chain",
                "Would be curious what sort of things came up in those 60s experiments though",
                "Yeah, ironically -- historically speaking the West has prized individualism a lot more in terms of invention but that leads to highly restrictive IP laws, which incentivizes innovation but also highly concentrates capital in the hands of original inventors",
                "That was their argument at least - not 100% sure what I think about it but I think there are definitely interesting tensions it surfaces - the default view from the West imo is to view copycat behavior in China in a purely derogatory way",
                "(Or in a negative light)",
                "Made me question how we define ‘innovation’",
                "Saffron Huang:",
                "mm yeah i see that. i feel like IP is like the definition of how the Western world sees innovation",
                "its about clearly defined novel discoveries that you can draw borders around",
                "i dont know if thats compatible with the kind of innovation that china is good at",
                "maybe it is, but there’s so much value placed on learning to replicate well - i dont know that that’s /not/ innovation",
                "i think maybe china is more explicit about the value of what’s past, about tradition and about mastery over it? the west has a novelty bias which can be good, but it is in a sense lying to itself",
                "nothing is truly novel right",
                "Jasmine Wang:",
                "Yeah I wonder if there are historical roots to that or if it’s a purely political move. There’s definitely at least a little bit of the latter - there’s a longstanding narrative since the Cold War that democracy + pure science ‘need’ each other, and by implication that innovation and more authoritarian governance is fundamentally incompatible",
                "This is a review link, not the actual paper-",
                "http://audrajwolfe.com/freedoms-laboratory/",
                "But Wolfe basically argues that the narrative of ‘scientific freedom’ was to some extent a tool of American government propagandists",
                "Definitely agree the US generally has a novelty bias",
                "(Or I guess the West ... I think it’s more true for the US though)",
                "Saffron Huang:",
                "i think its probably true that innovation in pure research is very difficult under authoritarianism",
                "but is that beside the point?",
                "Jasmine Wang:",
                "Tangential snark about the extent to which Silicon Valley is actually innovative from “What Tech Calls Thinking” -- “disruptive in precisely the way that Silicon Valley likes:“bombastic redescription of orthodoxy”, as the philosopher Daniel Dennett once put it”",
                "Saffron Huang:",
                "if the end goal of innovation is economic growth (that’s generally the presumed end goal), why do you necessarily have to start at advancing domestic pure science research to get to innovation to get to economic growth? seems like later developing countries need to do is prioritise catching up, and there’s a lot of work in political science on how authoritarianism can help with mobilising people for the massive changes/sacrifices needed to develop the economy. east asia is so frequently referred to as good examples of authoritarianism done well",
                "yeah i think pure science is sexy",
                "its easily propagandised",
                "vannevar bush, who is famous for advocating investing in science (he wrote “As We May Think”), knew how much engineering work needed to go into any technological advancement, as much as science did. but he decided to put the emphasis on promoting science because it’s more in line with western philosophical ideas of universality and truth than engineering is",
                "which has pretty much always been seen as a lower form of work in western culture - technicians and craftsmen are lower down on the totem pole than the brilliant scientists",
                "so i think thats part of the disdain for what china does?",
                "Jasmine Wang:",
                "interesting... like in order to move his reform suggestions through",
                "Yeah! the disdain is obviously also partially manufactured - China has been hugely successful in applied work and the US through this conceptual engineering can position itself as strictly better or more virtuous",
                "Saffron Huang:",
                "yeah its like, anything that can be proved through the western framework of the scientific method is more valid. it’s fair, its super useful",
                "Jasmine Wang:",
                "Applied science and engineering*",
                "Saffron Huang:",
                "the ‘US S&T work being strictly better or more virtuous’ idea reminds me of the attitudes towards traditional medicine and anything ‘holistic’ - if effects can’t be isolated it can’t be real",
                "both my parents do traditional chinese medicine i think i mentioned this earlier",
                "my dad also used to do surgery so it’s not like he sees them as fundamentally incompatible - he says you need a bit of both philosophies",
                "Jasmine Wang:",
                "😮 very interested in hearing about that, think there are so many limitations generally to Western medicine..",
                "Saffron Huang:",
                "yeah i’ve heard so many anecdotes throughout my life about ways they’ve healed people, and also myself... as a kid i did a bunch of rounds of acupuncture ON MY FACE and it improved my bad eyesight to 20/20... and the way they prescribe treatments is really holistic",
                "theres no way you can do double blind on that stuff",
                "Jasmine Wang:",
                "WHAT",
                "Saffron Huang:",
                "HAHA YES i used to fall asleep with needles on my face",
                "Jasmine Wang:",
                "Wait but you still have glasses",
                "Saffron Huang:",
                "yeah ok look",
                "college did a number on me",
                "anyway its like, traditional chinese medicine practitioners take as whole a view of the body as possible",
                "Jasmine Wang:",
                "I’d be very surprised if the journals that Matter and gatekeep What is Counted as Science change their policies on double blind any time soon",
                "Saffron Huang:",
                "and it’s interesting because in so many ways it’s so much like AI",
                "like the best neural nets these days just train on ALL THE DATA, you dont limit the inputs at all, and they generalise scary accurately to specific cases",
                "you throw the whole kitchen sink at it",
                "and it somehow is like, the epitome of western innovation",
                "and it’s so intransparent and no one knows what the heck is going on",
                "just like chinese medicine lmao",
                "Jasmine Wang:",
                "double standards! That’s really interesting, I just wish there were more shades of grey for what counts as contributions to our store of knowledge",
                "Definitely other interesting metaphors to surface from TCM as well - e.g. aiming towards harmony rather towards endless improvement (e.g. living forever) or progress in some more Western sense",
                "There’s this tension in the Chinese worldview that I’ve been thinking about - in some ways as reflected in TCM it’s less instrumental, more holistic/harmonious, but at the same time if you look at domestic policies, they’re in some way more utilitarian and much less rights-based",
                "Usually utilitarianism and instrumentality coincide",
                "Saffron Huang:",
                "hmm wait what do you mean",
                "Jasmine Wang:",
                "So like you said with TCM, they don’t view the body as purely instrumental, but holistically treat the entire self",
                "But often make utilitarian tradeoffs with respect to themselves and the way they coexist with others",
                "For example-",
                "For Americans, freedom of speech (+ the requisite privacy) and inviolable rights, but when I bring up surveillance and censorship on WeChat to relatives, they say, “but it’s so *convenient*”",
                "As in, they do care somewhat about privacy, and freedom of speech, but it’s not inviolable, it’s something to be weighed against convenience and the affordances WeChat allows",
                "Does that make sense? Potentially vague :”)",
                "Another anecdotal and slightly oppositional view (they think privacy is actually regarded as a bad thing in China)-",
                "https://www.scmp.com/news/hong-kong/article/2139946/why-privacy-alien-concept-chinese-culture",
                "Reading this article, I think the crux here is individualism, + that might resolve this apparent conflict.. many axes here and trying to figure out which variables correlate",
                "Saffron Huang:",
                "mmm right - more utilitarian, and less that there are clearly defined, inviolable rights/boundaries that it is always immoral to breach",
                "that’s very Effective Altruism in a sense - perhaps less altruistic, but definitely utilitarian",
                "(well, definitely less altruistic - from what i see chinese people are pretty bad at regarding people as universally worthy of care to them)",
                "i think you know about mohism right? its an ancient school of philosophy in china that advocated impartial love and universal welfare. it was competing against confucianism but ultimately lost... confucianism has VERY different ideas on altruism",
                "its seen as the earliest form of consequentialism and its just so wild that it happened in china, and how for sociopolitical reasons it was stamped out... clearly “progress” is not deterministic",
                "Jasmine Wang:",
                "Do you know for what sociopolitical reasons? Were utilitarian folks less ‘controllable’ by the state",
                "I’ve been trying to read up on different strands of Chinese philosophy",
                "https://www.noemamag.com/applying-ancient-chinese-philosophy-to-artificial-intelligence/",
                "This was quite good! main takeaway for me was that Confucianism, Daoism, and Buddhism are all non-anthropocentric; utilitarianism is anthropocentric intrinsically because it’s measured by the human experience of utility",
                "Saffron Huang:",
                "hmmm i think it just became somewhat irrelevant - lost social/political influence?",
                "Jasmine Wang:",
                "Hm got it 😛 guess there aren’t philosophical explanations for everything",
                "Yeah I’m definitely curious which philosophical stand is actually empirically best represented in the contemporary worldview of folks living in mainland China",
                "what do you think is the distribution of care over not-self humans for those in the US and for those in China?",
                "Saffron Huang:",
                "oh i like that article",
                "Jasmine Wang:",
                "also lol none of us are citizens of either place but it feels weird to say East/West",
                "Saffron Huang:",
                "“In Daoist teaching, where immortals abound, AI or digital beings could be just another form of super-being. Some Confucian and Daoist scholars have started thinking about incorporating AI into the ethical order of the ecosystem by potentially viewing AIs as companions or friends” this is kinda cute",
                "a super-friend",
                "yeah idk how idealistic/academic this is and whether people (esp those in tech...) actually think this way",
                "ooooh good question",
                "Jasmine Wang:",
                "love ‘super-friend’, fun contrast to ‘big Brother’",
                "Saffron Huang:",
                "I think from my experience in china/with my relatives, it’s like, people care so much about their family, so there’s a high level of care directed at few close people, and it declines the further away from the self you get",
                "The American distribution of altruism seem more fat-tailed in a sense because there’s not as much of a hard stop at ethnic boundaries... there’s not as much attention paid to the needs of non-Chinese",
                "that is, it seems Chinese people often don’t think it’s necessary to mind non-Chinese",
                "idk what u think?",
                "Jasmine Wang:",
                "yeah omg I wish there were a whiteboard but we could probably adapt the Dunbar circle here to a diagram of moral concern and it’d be self, family, friends, acquaintances, local ethnic groups, national, international",
                "I definitely +1 that in China there’s a discrete drop off between friends to acquaintances, and then from national and international",
                "I feel that the self --> family --> friends drop-off would be a lot flatter in China, something like self >>>> family >>> friends, whereas in the US it’s be strictly self >>>> family >> friends",
                "I’m not sure if the total ‘quantity’ of moral concern is strictly different but the distribution definitely feels  different",
                "Saffron Huang:",
                "its the mind-your-own-business, care for your family, just work hard set of values",
                "oh yeah this validates what we said about the distribution of care being v unequal",
                "https://www.lowyinstitute.org/the-interpreter/why-altruism-risky-china",
                "i also just found this about how youth are more into animal welfare these days, so it seems like they’re extending care beyond humans more, probably as a result of wealth increase and also western influence",
                "https://www.nationalgeographic.com/news/2017/07/wildlife-watch-china-changing-animal-protection/",
                "china is so full of contradictions",
                "Jasmine Wang:",
                "Oh interesting!!",
                "Saffron Huang:",
                "if the default state is not caring about animals much, that’s not particularly non-anthropocentric or Daoist, but definitely quite utilitarian",
                "so many contradictory strands"
            };
        private static string[] lines4 { get; } =
        {
                "Emily Markowitz:",
                "Regan, let’s talk about how the pandemic has changed our conception of time ",
                "Regan Brady:",
                "ooh yes I have a lot of thoughts about that ",
                "Emily Markowitz:",
                "I definitely think that in quarantine time felt that it was going by much quicker",
                "Regan Brady:",
                "yeah i agree- the spring felt like I was reliving the same day over and over ",
                "and i couldn’t tell you anything that happened to me this summer ",
                "Emily Markowitz:",
                "exactly, it molds together ",
                "imagine going on a run with someone who is showing you the way. The first time you do the run, it feels really long because everything your seeing feels new. You see a tree, you turn right, you see a store, and turn left there ",
                "But as you keep doing the run over and over again, it starts to feel quicker and quicker ",
                "because you begin cementing the categories in your mind ",
                "And I feel that quarantine is the same way ",
                "Regan Brady:",
                "yeah I totally agree with that ",
                "i think it’s bc so much of our sense of time is dependent on place/milestones/things changing",
                "Emily Markowitz:",
                "The categories become cemented - you wake up every day and do the same things over and over again ",
                "And so time seems to feel quicker ",
                "Regan Brady:",
                "usually I make spotify playlists to classify different periods of my life with like 50 songs that will take me back to the several month span that I make it for ",
                "and whenever i listen to it I am immediately transported back/relive the memories ",
                "Emily Markowitz:",
                "omg I feel that! ",
                "Regan Brady:",
                "over quarantine this summer though, i made like 5 playlists that all had a similar concept:days going by/going along/drifting through time. and all the songs sound the same and they dont remind me of anything lol ",
                "Emily Markowitz:",
                "when things don’t change, it all melds together ",
                "I think that we create our conception on time based on moments of change ",
                "start of college, end of the semester, winter break, etc ",
                "Regan Brady:",
                "do you feel like time is going by faster/slower now that we are not at home? ",
                "Emily Markowitz:",
                "Definitely slower! ",
                "My days feel longer ",
                "And it feels like I’ve been in Cambridge for a long time ",
                "Because there’s more that’s new ",
                "How about you? ",
                "Regan Brady:",
                "my days go by faster but my weeks are super slow. at home/in quarantine it was the opposite- every day was exactly the same and dragged on, but the weeks flew by ",
                "we have a team zoom call every thursday for my job, and that was my only marker of the passing of time this summer",
                "and the calls definitely felt much closer together in the summer than they do now ",
                "because there are more things that happen between them ",
                "Emily Markowitz:",
                "Do you like it better when time feels like it’s going by faster or slower? ",
                "Regan Brady:",
                "I’m definitely still in the student mindset of loving the action packed fully-scheduled days",
                "this makes me a little concerned about being an adult, since it’s all of the same aspects of quarantine that make time go by so fast (doing the same thing everyday, same routine, not as much movement/change on a day to day basis like we have in school) ",
                "Emily Markowitz:",
                "I’m so scared for adulthood because it becomes so repetitious ",
                "Regan Brady:",
                "i know. it’s scary now, but maybe at some point it changes and we learn to appreciate routine more ",
                "Emily Markowitz:",
                "Me too and also the 9-5 schedule every day is going to further exacerbate that ",
                "Perhaps we like routine more than entropy when we get older? ",
                "Regan Brady:",
                "there’s probably a difference between routine and boredom. but i definitely conflate the two",
                "Emily Markowitz:",
                "same here, I think there’s a complacency with routine ",
                "Also thinking about big markers that determine how we think about time ",
                "Looking at our life, it’s also marked by big markers ",
                "You graduate, get a job, get married, have a kid ",
                "Regan Brady:",
                "yeah i was also just thinking that there has probably been more that has happened in the last month or two (esp regarding politics) than over the summer ",
                "Emily Markowitz:",
                "Yes so much has happened nationally ",
                "While we’re all consuming stuck at home",
                "Regan Brady:",
                "i wonder how individual and collective experiences of time align- like does everyone feel that it’s slowed down with all that’s happening? or do the events in our own life matter more",
                "Emily Markowitz:",
                "That’s a really interesting thought ",
                "Also when we think about time passing in our own life, is it individual experiences or collective experiences that we think of more? ",
                "Regan Brady:",
                "my instinct would be that it’s the personal events that matter more, but even just looking at instagram memes, it seems like everyone felt like we were living the same day on repeat since march 13th haha ",
                "Emily Markowitz:",
                "Haha that’s true ",
                "Regan Brady:",
                "i wonder how we’ll look back at 2020 as a whole in 10 years ",
                "as a society",
                "Emily Markowitz:",
                "It’s also interesting to think about how time and space are connected with these large, collective experiences ",
                "For instance, everyone always knows where they were on 9/11 ",
                "Regan Brady:",
                "yes exactly! ",
                "Emily Markowitz:",
                "How society will remember 2020 and what parts will stand out more ",
                "Covid, Floyd protests? ",
                "Regan Brady:",
                "yeah- probably too soon to say with certainty since there’s still 2 more months to go ",
                "Emily Markowitz:",
                "ahhh",
                "The election results is the next thing... ",
                "Regan Brady:",
                "how do you personally remember 2020? ",
                "like when i think of it in my mind, its a mix of the personal and collective experiences kind of",
                "Emily Markowitz:",
                "definitely! out of all the years of my life, this one is most dominated by collective experiences",
                "Regan Brady:",
                "for me, going to europe with my dad in january stands out as the beginning of the year, then traveling to dallas, then visiting baltimore ",
                "Emily Markowitz:",
                "But makes sense because I’ve never had collective experiences impact my own plans so much ",
                "it started off early for me, was going to go to China but that got cancelled when Covid first started",
                "So got used to being resilient and having my plans canceled early one ",
                "*on",
                "Regan Brady:",
                "but after that, it’s being sent home from school, covid- like buying purell and lysolling the airplane seats, then fast forwards to the national protests, and then going to boston in september, and i can only guess that october will be characterized by whatever political events unfold ",
                "Emily Markowitz:",
                "Hahah ",
                "Regan Brady:",
                "yes I remember talking with you in the dhall about China being canceled 😟 ",
                "little did we know just a few short weeks later..... ",
                "Emily Markowitz:",
                "Maybe purell again since cases are surging? ",
                "Regan Brady:",
                "definitely masks ",
                "Emily Markowitz:",
                "Little did we know... ",
                "Regan Brady:",
                "how long will we keep wearing masks I wonder ",
                "will people start wearing them if they have a cold ",
                "Emily Markowitz:",
                "definitely some people for a long time ",
                "They keep you warm! ",
                "Regan Brady:",
                "theyre kind of nice now that its cold haha ",
                "they really do ",
                "Emily Markowitz:",
                "Haha honestly they’re a new market for clothing companies ",
                "So I can definitely see it being commercialized ",
                "Regan Brady:",
                "so true",
                "I see forever 21 selling mask/sweatpant/sweatshirt matching sets ",
                "kind of tempted to buy one ",
                "Emily Markowitz:",
                "Hahaha next start up idea?",

            };

        private static string[] feed0 { get; } = {
            "Eli Burnes:",
            "Dude what do you think of contemporary interior design / architecture. Like the aesthetic of all the new coffee shops",
            "Tunc Otzemir:",
            "I think it’s good for the cafes",
            "It is nice but not super cozy" };
        private static string[] feed1 { get; } = {
            "Kush Sharma:",
            "Creating guilt among the powerful functions in a fractal way. The aristocrats of the Roman republic had the same internal dynamics - e.g. Gaius Marius, a low-born but extremely competent military general who denounced the high aristocracy of his day for responding to crises with haughty arrogance that didn't correspond to their abilities. They had power, but competence isn't hereditary like power is/was, so the critiques hit on a legitimate point.",
            "Eli Burnes:",
            "What do you mean by fractal?" };
        private static string[] feed2 { get; } = {
            "Jasmine Wang:",
            "china is so full of contradictions ",
        };
        private static string[] feed3 { get; } = {
            "Ethan Fields:",
            "Even prior to the pandemic, the art and museum world was in a state of flux as institutions were critiqued for accepting dubious donations",
            "So the board members clearly wanted to mitigate any sense of controversy that could have exposed them to public dissatisfaction",
            "Caleb Rhodes:",
            "Yeah this is definitely a defensive move, but was it motivated by money or just fear of outrage?" };
        private static string[] feed4 { get; } = {
            "Emily Markowitz:",
            "I definitely think that in quarantine time felt that it was going by much quicker",
            "Regan Brady:",
            "yeah i agree- the spring felt like I was reliving the same day over and over",
            "and honestly, i couldn’t tell you anything that happened to me this summer",
            "Emily Markowitz:",
            "exactly, it molds together" };
        private static string[] feed5 { get; } = {
            "Ian Liefer:",
            "Why do you think Biden is gonna win?",
            "Trump has unprecedented black and Latino support",
            "And hasn’t lost any of his base",
            "Henry Burnes:",
            "elderly people and suburban women are going for Biden, two critical demographics for Trump",
            "Ian Liefer:",
            "but it’s unclear if the data supports that in key swing states" };
        private static string[] feed6 { get; } = {
            "Eli Burnes:",
            "The culture of the nouveau riche is taking over. Because “class” as a state of mind and manners is less and less respected",
            "Simpler and more vulgar ways are being used to assert dominance and prestige" };


        private static string title0 { get; } =
            "coffehouse vibe";

        private static string title1 { get; } =
            "Nietzsche x Wokeism";

        private static string title2 { get; } =
            "China, culture, innovation";

        private static string title3 { get; } =
            "culture of timidity";

        private static string title4 { get; } =
            "time x quarintine";

        private static string title5 { get; } =
            "Election predictions";

        private static string title6 { get; } =
            "Majoritarian rule in America";


        private static string poster0 { get; } =
            "Eli Burnes";

        private static string poster1 { get; } =
            "Kush Sharma";

        private static string poster2 { get; } =
            "Saffron Huang";

        private static string poster3 { get; } =
            "Caleb Rhodes";

        private static string poster4 { get; } =
            "Regan Brady";

        private static string poster5 { get; } =
            "Henry Burnes";

        private static string poster6 { get; } =
            "Marshall Sloane";

        private static int[] replies0 { get; } = {
            2,5
        };

        private static int[] replies1 { get; } = {
            1,3,4
        };

        private static int[] replies2 { get; } = {
            1
        };

        private static int[] replies3 { get; } = {
            6
        };

        private static int[] replies4 { get; } = {

        };

        private static int[] replies5 { get; } = {
        };
        private static int[] replies6 { get; } = {
        };
        //string[] lines, string title, string poster, string[] preview

        static LoadFeedConvos()
        {

            ConvoList.Add(new PublicConvo(lines0, title0, poster0, feed0, LoadComments.CommentsList[0], replies0));
            ConvoList.Add(new PublicConvo(lines1, title1, poster1, feed1, LoadComments.CommentsList[1], replies1));
            ConvoList.Add(new PublicConvo(lines2, title2, poster2, feed2, LoadComments.CommentsList[2], replies2));
            ConvoList.Add(new PublicConvo(lines3, title3, poster3, feed3, LoadComments.CommentsList[3], replies3));
            ConvoList.Add(new PublicConvo(lines4, title4, poster4, feed4, LoadComments.CommentsList[4], replies4));
            ConvoList.Add(new PublicConvo(lines5, title5, poster5, feed5, LoadComments.CommentsList[5], replies5));
            ConvoList.Add(new PublicConvo(lines6, title6, poster6, feed6, LoadComments.CommentsList[6], replies6));

        }
    }
}
