using System;
using System.Collections.Generic;
using System.Reflection.Metadata.Ecma335;

namespace uiExp.Shared
{
    public class LoadDms
    {
        public static List<PrivateMessage> InboxList = new List<PrivateMessage>();

        private static string[] lines0 { get; } =
            {
                "Marshall Sloane:",
                "Majoritarian politics commanding the morals is what trump is about rejecting",
                "It’s a righteous mission if he weren’t a racist buffoon ",
                "Eli Burnes:",
                "hmmm",
                "Marshall Sloane:",
                "The tea party is just tired of majoritarian tyranny ",
                "I’ve been saying this for a while",
                "Eli Burnes:",
                "Who is the majority",
                "Marshall Sloane:",
                "The woke",
                "Who command industry and schools",
                "Eli Burnes:",
                "But the woke are a minority",
                "Marshall Sloane:",
                "And government ",
                "Eli Burnes:",
                "With power",
                "Marshall Sloane:",
                "But they are a majority of noise",
                "Eli Burnes:",
                "true",
                "That’s the irony",
                "Marshall Sloane:",
                "They command press, schools, and industry ",
                "We live in a society governed by majoritarian tyranny of the woke",
                "It troubles me often",
                "Eli Burnes:",
                "hah",
                "Insane how ever corporation made a statement on BLM",
                "Marshall Sloane:",
                "Yup",
                "Eli Burnes:",
                "Radical politics is establishment politics",
                "Marshall Sloane:",
                "Yes and no",
                "Eli Burnes:",
                "Status quo",
                "Marshall Sloane:",
                "It’s not radical it’s very tame ",
                "Eli Burnes:",
                "That’s the point",
                "*my point",
                "Marshall Sloane:",
                "French Revolution, libya, Egypt, China",
                "Those were radical ",
                "Ours is so tame",
                "Marching, rioting ",
                "Isn’t wild",
                "It’s childish",
                "Eli Burnes:",
                "yep",
                "Marshall Sloane:",
                "There is no radical reforming of ideas",
                "No robust idea on a reformulation of society besides vomiting up washed up socialist speak that has never worked",
                "Eli Burnes:",
                "Isn’t that the history of antiracism though, like blacks just want to be treated like whites",
                "Marshall Sloane:",
                "But they are",
                "By and large",
                "Eli Burnes:",
                "So it doesn’t require radical rethinking to suceed",
                "That’s fiar",
                "But discrepancies are still absurd wrt poverty, incarceration, crime etc.",
                "Police are a straw man in all of this perhaps",
                "A scapegoat",
                "Marshall Sloane:",
                "That’s the issue. Our majoritarian politics validates their stance, but nothing changes. Wealth and class don’t change. Their criminality doesn’t change. So they’re just overwhelmed by this lethargic creep towards our countries eventual realization that nothing can be done besides their effort to fall into American conformism until they flourish too. ",
                "I wonder when that day will come.",
                "Marshall Sloane:",
                "Because, the feature left out is that in order to be treated as a white you in fact need to act like oneZ",
                "That may sound heinous ",
                "But it’s the functioning of American societt",
                "Eli Burnes:",
                "Hm that makes sense interesting interpretation, so success in america requires conformism on your view",
                "Marshall Sloane:",
                "Entirely",
                "It’s how we operate",
                "Eli Burnes:",
                "Asian Americans, are they conformist?",
                "Marshall Sloane:",
                "We are a conformist society",
                "Yes",
                "Entirely",
                "Eli Burnes:",
                "But they do it to an extreme",
                "Marshall Sloane:",
                "But it’s conformism to an idea. That’s why there is such anxiety between immigrants and natives, right? If each immigrant class strives to do better, then the prior class will stagnate and be left behind - fueling this cycle of anxiety.",
                "Eli Burnes:",
                "Hm",
                "Marshall Sloane:",
                "Blacks got the worst of the stick. They - like many whites - are left behind. But they didn’t have the class and wealth to still rise up.",
               "Like some WASPS are still rich. It isn’t just more recent immigrants",
                "Because class is still currency here.",
                "Eli Burnes:",
                "true.",
                "Wasp society is decadent though",
                "Dying and fracturing",
                "Marshall Sloane:",
                "I suppose",
                "We live in a society where clout govern",
                "And without their clout they’re imploding and resorting to normal means of achieving clout",
                "Which is flashing money",
                "Eli Burnes:",
                "haha",
                "The culture of the nouveau riche is taking over. Because “class” as a state of mind and manners is less and less respected",
                "Simpler and more vulgar ways are being used to assert dominance and prestige",
                "Marshall Sloane:",
                "Yes",
                "Majoritarian rule in America"
            };



            private static string[] lines1 { get; } =
            {
                "Eli Burnes:",
                "\"They stalk about in our midst as living reproaches, as warnings to us—as though health, fitness, strength, pride, the sensation of power, were really vicious things in themselves, for which one would have some day to do penance, bitter penance. Oh, how they themselves are ready in their hearts to exact penance, how they thirst after being hangmen! (GM III 14)\"",
                "Here Nietzsche describes the revolt of the lowly, the oppressed, against the strong",
                "He thinks the less powerful have succeed by making the powerful guilty – guilty for their power",
                "The psychological trick of of the oppressed, on Nietzsche’s view, is to make the attributes of the powerful seem ridiculous, cause for guilt",
                "Can we compare this to modern notions of privilege?",
                "Kush Sharma:",
                "Creating guilt among the powerful functions in a fractal way. The aristocrats of the Roman republic had the same internal dynamics - e.g. Gaius Marius, a low-born but extremely competent military general who denounced the high aristocracy of his day for responding to crises with haughty arrogance that didn't correspond to their abilities. They had power, but competence isn't hereditary like power is/was, so the critiques hit on a legitimate point.",
                "Eli Burnes:",
                "What do you mean by fractal?",
                "Kush Sharma:",
                "Just like the bottom of the bottom (e.g. Jesus and the Jews) were able to critique one level up - establishment Jewish rabbis + the Roman administrators, the same dynamics were occurring within the highest reaches (and maybe occur in every local class / power conflict?)",
                "Eli Burnes:",
                "Hmm interesting",
                "Kush Sharma:",
                "Interesting comparison to upper middle class vs global elite, white lower class vs black / brown underclass?",
                "Elites seem to be failing - globalization didn't live up to its promises, at least for those who already lived in wealthy Western countries. Technology is stagnating. There are legit critiques of competence, but maybe easier to dress those critiques up in moral terms - BLM, privilege, wokeness?",
                "Eli Burnes:",
                "Yeah. To your last text–people see themselves in the context of their local hierarchies. for everyone, there’s always a more powerful group and a less powerful group. There’s research that suggests people compare their incomes to those around them. to someone in the upper middle class the excessive wealth of the elite elite might invoke jealousy + condemnation.",
                "Moral/psychological memes are perhaps the most effective way for the powerless to gain power/challenge those in power. Nietzsche totally understands this",
                "Kush Sharma:",
                "Ahhh yes, and that means that whoever is one level up in the apparent hierarchy becomes the",
                "*oops more to come",
                "\"enemy\" and all levels above that are illegible to the person at a particular local level. One explanation for why the Trump demo's anger has been aimed at those one below (illegal immigrants, POC lower / under class) and one above (liberal academics, professional / managerial class); and that anger was leveraged by right elites.",
                "Does the dominance of a moral / psych meme imply that it is more truthful or moral? Or does it just imply greater memetic fitness?",
                "Eli Burnes:",
                "Ohh interesting take on trump. Certainly true that his anti elite rhetoric does not target the rich + most powerful in the way that Warren’s did in her primary campaign. she has a different audience",
                "The wokeism meme (which is quite complex, of course) may not be that fit–it might just fizzle out. But by definition it’s been super high fitness up to this point",
                "Don’t think dominance implies truth",
                "But it does suggest that it fit’s nicely into previously established belief systems/memeplexes",
                "For instance wokeism thrives on the generally accepted idea (in Western European liberalism) that equality is the most important moral standard/ideal",
                "And the basic equality of humans the fundamental moral fact",
                "Moral/psych memes have to seem true, at least",
                "my view is that morality is socially constructed (to some extent) so being dominant means participating in constructing morality at least",
                "Kush Sharma:",
                "Yep! The fitness of wokeism is super interesting - my take is that it's not fit, because it misunderstood the basic nature of power in a capitalist system. Power in the US doesn't come from political activism, protests, or governmental bodies; all the areas where wokeness has gained some power. All those are subservient to capital or irrelevant int he face of capital - see wokeism being coopted by F500s and rejected by entrepreneurs. Ofc future forecasts are always hand wavy though :)",
                "Ya, and it hit trouble when it contradicted another deeply held moral fact - freedom of speech and expression (esp in the US)",
                "Being a part of the dominant morality gives you cultural capital - interesting dynamics occur when (mainstream) cultural capital is less and less valuable",
                "Eli Burnes:",
                "Yes wokeism seems to me to be not that effective in terms of real political gains for black people–massive investment in poor, black, urban areas, for instance, is badly needed but nowhere in sight. We’ll see if the police reforms we get are actually effective and fair or are not...",
                "Freedom of speech and expression might not be the biggest roadblock to wokeism– it runs up against humanism, to some extent we should see people first as human beings and only second as people of a certain race. It also feels christian. There’s heresy, apostates, original sin (slavery). Not sure if this is good for fitness or not–we live in a secular culture but puritanism is still quite dominant. Any resistance movement meets backlash, gains for black people in the US seem always to be met with pushback from whites. Maybe wokeism will succeed because it changes what type of push back is acceptable. wokeism undermines the foundation of white power by making white people question their privilege–often to an insane degree. ",
                "Kush Sharma:",
                "Yeah! It's post-Christianity Christianity, but without Salvation! It fills ~80% of the gap Christianity left in the culture, but without offering metaphysics or \"ultimate\" morality - it only offers relative, \"profane\" social morality. It's redistributionist rather than growth-oriented.",
                "Yep I think that's fair and it will succeed in making gains for black people, but at the expense of cultural progress as a whole. MLK-style civil rights didn't have this drawback, and even Malcolm X-style secession didn't as much - one focused on unity, not guilt, and the other focused on internal strength and exit, not voice",
                "Difficult to say if progress (for black people) is possible without the guilt though - a huge part of the guilt is baked into the social reality of the last 200y, and needs to be confronted and processed by the culture",
                "Eli Burnes:",
                "good point on salvation. By definition, psychological purification from white supremacy (a sort of salvation or redemption) is not possible. And the apparent goal of the present racial justice movement–exact equity in all social outcomes between whites and blacks–is frankly not possible, unless we get to a world in which race matters not at all. There seems to be no endpoint.",
                "I think white guilt might actually be doing some effective things",
                "Kush Sharma:",
                "Yep - maybe then the question is one of attention allocation between different causes? Social / racial justice is needed, but with 10 other causes that are equally if not more pressing (stagnation, climate change, ex-risk, etc) allocating all our cultural attention to a cause that's inherently zero-sum and profane rather than positive-sum and sacred seems dangerous",
                "Eli Burnes:",
                "Here’s an example. I think that education is the most effective way for wealthy white people to maintain their family’s power–paying for private school may be more effective than a trust fund. Insofar as this is true, wokeism might be working, because it undermines the idea that white people should be able to use money to get better education. Woke white parents are getting uncomfortable maintaining their family’s privilege–their guilt might lead to material and psychological solidarity with non white people.",
                "For sure, attention allocation this summer shifted almost entirely (at least in white managerial class) to racial justice, evidenced by NYT bestsellers. Not sure racial justice get’s too much attention, of course it often hasn’t gotten enough.  But perhaps it wasn’t a good use of attention in the summer leading up to the election.",
                "What can we pay attention to that’s sacred?",
                "Kush Sharma:",
                "Isn't non-zero sum privilege desirable though? If private school is just a grift to help your kid get into Harvard easier (which in many cases it is which is where this is super valid), that's not a great form of privilege. But if private school is a superior education that allows your kid to contribute in a more valuable way to society, then despite the fact that privilege creates privilege, it also creates competence, which should be positive-sum. Then white guilt is actively destructive!",
                "I'd say it's hard to find things that are collectively sacred at the level of Christianity until / if new forms of religion appear, but I think there are things that are more sacred. Elon-esque human expansion across the universe, scientific progress, localism over national / global politics & rebuilding communities, a \"holy war\" against climate change",
                "Eli Burnes:",
                "Oh for sure I agree. Guilt like this about schools can be destructive. Parents are literally denying their kids opportunities because many black people don’t get to have them. The obvious solution is to make the opportunity available to black + white people! racial justice is not necessarily zero sum, but that’s how it’s playing out in the streets and in the pages of the NYT...",
                "^ reply to your first text",
                "I think some of the appeal of racial justice is that it feels sacred",
                "Kush Sharma:",
                "For sure! I do have to run now but this was awesome, had a great time and think we came up with some dope ideas :)",
                "Eli Burnes:",
                "Great talk man",
                "Nietzsche x Wokeism"
            };

           
        private static string[] lines2 { get; } =
        {
                "Eli Burnes:",
                "Dude what do you think of contemporary interior design / architecture. Like the aesthetic of all the new coffee shops",
                "Like incandescent lights, white walls, chalkboard menus, maybe plants",
                "Tunc Otzemir:",
                "I think it’s good for the cafes",
                "Eli Burnes:",
                "How so",
                "It’s kind of nice",
                "Comforting",
                "Tunc Otzemir:",
                "It is nice but not super cozy",
                "Eli Burnes:",
                "cold",
                "Tunc Otzemir:",
                "And promotes an atmosphere in which ppl are prompted to leave in a reasomable time",
                "Which is good for then",
                "But i do like the extremely cozy, home like, never leave kinda places",
                "Eli Burnes:",
                "ah",
                "Me too",
                "Tunc Otzemir:",
                "Esp if u wanna work or sit around and chat",
                "this is like emblematic of the focus on productivity",
                "Eli Burnes:",
                "yes",
                "They are almost designed for a quick business meeting",
                "Tunc Otzemir:",
                "like come get your coffee enjoy a beautiful, therapeutic space for half an hour or so",
                "Eli Burnes:",
                "Or a quick phone call",
                "Tunc Otzemir:",
                "And move on to your actual life or whatever gif",
                "Gig u need to do",
                "Yeah",
                "Eli Burnes:",
                "The lights and the greenery give a sort of fake homey vibe",
                "Tunc Otzemir:",
                "Like i think esp the design of the seated spaces are the most important in determining the longetivity of the stay",
                "Eli Burnes:",
                "hm",
                "Tunc Otzemir:",
                "I think not homey but, fake outdoorsy. So you will feel refreshed",
                "Eli Burnes:",
                "ah",
                "Tunc Otzemir:",
                "Cause the cozy places are usually dark and not soul nurturing",
                "They are like libraries and homes mixture",
                "Eli Burnes:",
                "Why isn’t that soul nurturing",
                "Tunc Otzemir:",
                "I mean it is",
                "But if you’re taking a quick break from work to get coffee or whatever",
                "You need a lot of light",
                "To make u feel like you’re in a park or sth",
                "Eli Burnes:",
                "yep",
                "Tunc Otzemir:",
                "This space is gorgeous tho the one u sent",
                "But most of the times it is implemeted badly",
                "Eli Burnes:",
                "Yeah fair",
                "Tunc Otzemir:",
                "Would you say blue bottle has a similar design?",
                "Eli Burnes:",
                "Like the places in the smith center",
                "Tunc Otzemir:",
                "For example I hate that place",
                "I feel like I am in a factory it’s overcrowded, everyone is uncomfortably seated",
                "Eli Burnes:",
                "Looking through the window is like looking into a fishbowl",
                "An auarium",
                "*aquarium",
                "It has lots of wood and light",
                "Super white",
                "You think the seats make people stay for less time",
                "The spaces feel so professional and overly designed it gives the sense that there’s now way they could mess up your order, that nothing could go wrong",
                "Like a fancy hospital",
                "Tunc Otzemir:",
                "Yeah I agree",
                "It is like a high tech factory",
                "Eli Burnes:",
                "Haha",
                "Tunc Otzemir:",
                "I want my order to have the possibility of being messed up",
                "That means there is actual human care and labor that goes into it",
                "Eli Burnes:",
                "Yes",
                "Tunc Otzemir:",
                "And that there exists a possibility that when it is not messed up",
                "It will be provided with care and love rather then precision",
                "Like u know they're also cutting costs on everything in these kinda of places",
                "coffehouse vibe"
            };

        private static string[] lines3 { get; } =
        {
            "Jonah Berger:",
            "https://twitter.com/sahilkapur/status/1332411155701264391?s=10",
            "Kind of crazy!",
            "Noah Redlich:",
            "That is crazy!! ",
            "I’m a bit skeptical of exit polls this year tho ",
            "Eli Burnes:",
            "Surprise! Voters are pragmatically rational!",
            "Noah Redlich:",
            "I feel like they can’t be as accurate because of all the absentee voting ",
            "Eli Burnes:",
            "If the rich weren’t manipulating the media, brainwashing Americans to believe in the American dream, and voting in droves for republicans, the masses would elect a president who would take from the rich and give to the poor",
            "Like Bernie",
            "And it would be awful",
            "Noah Redlich:",
            "Exactly!! ",
            "Eli Burnes:",
            "!",
            "Noah Redlich:",
            "Hahahahaha",
            "Eli Burnes:",
            "Thoughts on student loan debt forgiveness?",
            "Im prima facie against it",
            "Noah Redlich:",
            "I’m for it ",
            "I hate the right wing talking point that it’s a bailout of the rich ",
            "Most people with student debt are working class ",
            "Eli Burnes:",
            "Intersting",
            "Didn’t know that",
            "Jonah Berger:",
            "But they live in cities",
            "Eli Burnes:",
            "Most people also don’t go to college",
            "Jonah Berger:",
            "We need to give money to republicans",
            "Eli Burnes:",
            "yes",
            "Jonah Berger:",
            "Bribe them to vote for us",
            "Eli Burnes:",
            "We can’t just forgive the debt of the educated class, how is that fair to working class people who passed on a 4 year liberal arts degree to hit the job market?",
            "Pragmatically, it would be good for the economy and for our generation",
            "Optics are bad re: culture war",
            "Campbell Erickson:",
            "Lol true",
            "Eli Burnes:",
            "https://twitter.com/PrinceVogel/status/1299886882139058177?s=20",
            "Jonah Berger:",
            "Lol if we only forgave black people’s debt there would be a civil war",
            "Eli Burnes:",
            "Reparations !",
            "The higher education industry has collectively ripped off so many heads",
            "Its just too damn expensive" };
        private static string user = "Eli Burnes";

        static LoadDms()
        {
            InboxList.Add(new PrivateMessage(lines0, user));
            InboxList.Add(new PrivateMessage(lines1, user));
            InboxList.Add(new PrivateMessage(lines2, user));
            InboxList.Add(new PrivateMessage(lines3, user));

        }
    }
}
