using System;
using System.Collections.Generic;
using System.Reflection.Metadata.Ecma335;

namespace uiExp.Shared
{
    public class LoadDms
    {
        //in these convos, replaced Eli with sahil, sahil with noah redlich...

        public static List<PrivateMessage> InboxList = new List<PrivateMessage>();

        private static string[] lines0 { get; } =
            {
                "Marshall Sloane:",
                "Majoritarian politics commanding the morals is what trump is about rejecting",
                "It’s a righteous mission if he weren’t a racist buffoon ",
                "Sahil Handa:",
                "hmmm",
                "Marshall Sloane:",
                "The tea party is just tired of majoritarian tyranny ",
                "I’ve been saying this for a while",
                "Sahil Handa:",
                "Who is the majority",
                "Marshall Sloane:",
                "The woke",
                "Who command industry and schools",
                "Sahil Handa:",
                "But the woke are a minority",
                "Marshall Sloane:",
                "And government ",
                "Sahil Handa:",
                "With power",
                "Marshall Sloane:",
                "But they are a majority of noise",
                "Sahil Handa:",
                "true",
                "That’s the irony",
                "Marshall Sloane:",
                "They command press, schools, and industry ",
                "We live in a society governed by majoritarian tyranny of the woke",
                "It troubles me often",
                "Sahil Handa:",
                "hah",
                "Insane how ever corporation made a statement on BLM",
                "Marshall Sloane:",
                "Yup",
                "Sahil Handa:",
                "Radical politics is establishment politics",
                "Marshall Sloane:",
                "Yes and no",
                "Sahil Handa:",
                "Status quo",
                "Marshall Sloane:",
                "It’s not radical it’s very tame ",
                "Sahil Handa:",
                "That’s the point",
                "*my point",
                "Marshall Sloane:",
                "French Revolution, libya, Egypt, China",
                "Those were radical ",
                "Ours is so tame",
                "Marching, rioting ",
                "Isn’t wild",
                "It’s childish",
                "Sahil Handa:",
                "yep",
                "Marshall Sloane:",
                "There is no radical reforming of ideas",
                "No robust idea on a reformulation of society besides vomiting up washed up socialist speak that has never worked",
                "Sahil Handa:",
                "Isn’t that the history of antiracism though, like blacks just want to be treated like whites",
                "Marshall Sloane:",
                "But they are",
                "By and large",
                "Sahil Handa:",
                "So it doesn’t require radical rethinking to suceed",
                "That’s fiar",
                "But discrepancies are still absurd wrt poverty, incarceration, crime etc.",
                "Police are a straw man in all of this perhaps",
                "A scapegoat",
                "Marshall Sloane:",
                "That’s the issue. Our majoritarian politics validates their stance, but nothing changes. Wealth and class don’t change. Their criminality doesn’t change. So they’re just overwhelmed by this lethargic creep towards our countries eventual realization that nothing can be done besides their effort to fall into American conformism until they flourish too. ",
                "I wonder when that day will come.",
                "Marshall Sloane:",
                "Because, the feature left out is that in order to be treated as a white you in fact need to act like oneZ",
                "That may sound heinous ",
                "But it’s the functioning of American societt",
                "Sahil Handa:",
                "Hm that makes sense interesting interpretation, so success in america requires conformism on your view",
                "Marshall Sloane:",
                "Entirely",
                "It’s how we operate",
                "Sahil Handa:",
                "Asian Americans, are they conformist?",
                "Marshall Sloane:",
                "We are a conformist society",
                "Yes",
                "Entirely",
                "Sahil Handa:",
                "But they do it to an extreme",
                "Marshall Sloane:",
                "But it’s conformism to an idea. That’s why there is such anxiety between immigrants and natives, right? If each immigrant class strives to do better, then the prior class will stagnate and be left behind - fueling this cycle of anxiety.",
                "Sahil Handa:",
                "Hm",
                "Marshall Sloane:",
                "Blacks got the worst of the stick. They - like many whites - are left behind. But they didn’t have the class and wealth to still rise up.",
               "Like some WASPS are still rich. It isn’t just more recent immigrants",
                "Because class is still currency here.",
                "Sahil Handa:",
                "true.",
                "Wasp society is decadent though",
                "Dying and fracturing",
                "Marshall Sloane:",
                "I suppose",
                "We live in a society where clout govern",
                "And without their clout they’re imploding and resorting to normal means of achieving clout",
                "Which is flashing money",
                "Sahil Handa:",
                "haha",
                "The culture of the nouveau riche is taking over. Because “class” as a state of mind and manners is less and less respected",
                "Simpler and more vulgar ways are being used to assert dominance and prestige",
                "Marshall Sloane:",
                "Yes. this is just example text for inbox. it comes down for the decline in the wasp mentality and the ascendance of people of all creeds who do not ascribe to new england puritanism, an ideology which allowed aristocratic values to stick around into modernity."
            };

            private static string[] lines1 { get; } =
            {
                "Sahil Handa:",
                "\"They stalk about in our midst as living reproaches, as warnings to us—as though health, fitness, strength, pride, the sensation of power, were really vicious things in themselves, for which one would have some day to do penance, bitter penance. Oh, how they themselves are ready in their hearts to exact penance, how they thirst after being hangmen! (GM III 14)\"",
                "Here Nietzsche describes the revolt of the lowly, the oppressed, against the strong",
                "He thinks the less powerful have succeed by making the powerful guilty – guilty for their power",
                "The psychological trick of of the oppressed, on Nietzsche’s view, is to make the attributes of the powerful seem ridiculous, cause for guilt",
                "Can we compare this to modern notions of privilege?",
                "Kush Sharma:",
                "Creating guilt among the powerful functions in a fractal way. The aristocrats of the Roman republic had the same internal dynamics - e.g. Gaius Marius, a low-born but extremely competent military general who denounced the high aristocracy of his day for responding to crises with haughty arrogance that didn't correspond to their abilities. They had power, but competence isn't hereditary like power is/was, so the critiques hit on a legitimate point.",
                "Sahil Handa:",
                "What do you mean by fractal?",
                "Kush Sharma:",
                "Just like the bottom of the bottom (e.g. Jesus and the Jews) were able to critique one level up - establishment Jewish rabbis + the Roman administrators, the same dynamics were occurring within the highest reaches (and maybe occur in every local class / power conflict?)",
                "Sahil Handa:",
                "Hmm interesting",
                "Kush Sharma:",
                "Interesting comparison to upper middle class vs global elite, white lower class vs black / brown underclass?",
                "Elites seem to be failing - globalization didn't live up to its promises, at least for those who already lived in wealthy Western countries. Technology is stagnating. There are legit critiques of competence, but maybe easier to dress those critiques up in moral terms - BLM, privilege, wokeness?",
                "Sahil Handa:",
                "Yeah. To your last text–people see themselves in the context of their local hierarchies. for everyone, there’s always a more powerful group and a less powerful group. There’s research that suggests people compare their incomes to those around them. to someone in the upper middle class the excessive wealth of the elite elite might invoke jealousy + condemnation.",
                "Moral/psychological memes are perhaps the most effective way for the powerless to gain power/challenge those in power. Nietzsche totally understands this",
                "Kush Sharma:",
                "Ahhh yes, and that means that whoever is one level up in the apparent hierarchy becomes the",
                "*oops more to come",
                "\"enemy\" and all levels above that are illegible to the person at a particular local level. One explanation for why the Trump demo's anger has been aimed at those one below (illegal immigrants, POC lower / under class) and one above (liberal academics, professional / managerial class); and that anger was leveraged by right elites.",
                "Does the dominance of a moral / psych meme imply that it is more truthful or moral? Or does it just imply greater memetic fitness?",
                "Sahil Handa:",
                "Ohh interesting take on trump. Certainly true that his anti elite rhetoric does not target the rich + most powerful in the way that Warren’s did in her primary campaign. she has a different audience",
                "The wokeism meme (which is quite complex, of course) may not be that fit–it might just fizzle out. But by definition it’s been super high fitness up to this point",
                "Don’t think dominance implies truth",
                "But it does suggest that it fit’s nicely into previously established belief systems/memeplexes",
                "For instance wokeism thrives on the generally accepted idea (in Western European liberalism) that equality is the most important moral standard/ideal",
                "And the basic equality of humans the fundamental moral fact",
                "Moral/psych memes have to seem true, at least",
                "my view is that morality is socially constructed (to some extent) so being dominant means participating in constructing morality at least",
                "Kush Sharma:",
                "Yep! The fitness of wokeism is super interesting - my take is that it's not fit, because it misunderstood the basic nature of power in a capitalist system. Power in the US doesn't come from political activism, protests, or governmental bodies; all the areas where wokeness has gained some power. All those are subservient to capital or irrelevant int he face of capital - see wokeism being coopted by F500s and rejected by entrepreneurs. Ofc future forecasts are always hand wavy though :)",
                "Ya, and it hit trouble when it contradicted another deeply held moral fact - freedom of speech and expression (esp in the US)",
                "Being a part of the dominant morality gives you cultural capital - interesting dynamics occur when (mainstream) cultural capital is less and less valuable",
                "Sahil Handa:",
                "Yes wokeism seems to me to be not that effective in terms of real political gains for black people–massive investment in poor, black, urban areas, for instance, is badly needed but nowhere in sight. We’ll see if the police reforms we get are actually effective and fair or are not...",
                "Freedom of speech and expression might not be the biggest roadblock to wokeism– it runs up against humanism, to some extent we should see people first as human beings and only second as people of a certain race. It also feels christian. There’s heresy, apostates, original sin (slavery). Not sure if this is good for fitness or not–we live in a secular culture but puritanism is still quite dominant. Any resistance movement meets backlash, gains for black people in the US seem always to be met with pushback from whites. Maybe wokeism will succeed because it changes what type of push back is acceptable. wokeism undermines the foundation of white power by making white people question their privilege–often to an insane degree. ",
                "Kush Sharma:",
                "Yeah! It's post-Christianity Christianity, but without Salvation! It fills ~80% of the gap Christianity left in the culture, but without offering metaphysics or \"ultimate\" morality - it only offers relative, \"profane\" social morality. It's redistributionist rather than growth-oriented.",
                "Yep I think that's fair and it will succeed in making gains for black people, but at the expense of cultural progress as a whole. MLK-style civil rights didn't have this drawback, and even Malcolm X-style secession didn't as much - one focused on unity, not guilt, and the other focused on internal strength and exit, not voice",
                "Difficult to say if progress (for black people) is possible without the guilt though - a huge part of the guilt is baked into the social reality of the last 200y, and needs to be confronted and processed by the culture",
                "Sahil Handa:",
                "good point on salvation. By definition, psychological purification from white supremacy (a sort of salvation or redemption) is not possible. And the apparent goal of the present racial justice movement–exact equity in all social outcomes between whites and blacks–is frankly not possible, unless we get to a world in which race matters not at all. There seems to be no endpoint.",
                "I think white guilt might actually be doing some effective things",
                "Kush Sharma:",
                "Yep - maybe then the question is one of attention allocation between different causes? Social / racial justice is needed, but with 10 other causes that are equally if not more pressing (stagnation, climate change, ex-risk, etc) allocating all our cultural attention to a cause that's inherently zero-sum and profane rather than positive-sum and sacred seems dangerous",
                "Sahil Handa:",
                "Here’s an example. I think that education is the most effective way for wealthy white people to maintain their family’s power–paying for private school may be more effective than a trust fund. Insofar as this is true, wokeism might be working, because it undermines the idea that white people should be able to use money to get better education. Woke white parents are getting uncomfortable maintaining their family’s privilege–their guilt might lead to material and psychological solidarity with non white people.",
                "For sure, attention allocation this summer shifted almost entirely (at least in white managerial class) to racial justice, evidenced by NYT bestsellers. Not sure racial justice get’s too much attention, of course it often hasn’t gotten enough.  But perhaps it wasn’t a good use of attention in the summer leading up to the election.",
                "What can we pay attention to that’s sacred?",
                "Kush Sharma:",
                "Isn't non-zero sum privilege desirable though? If private school is just a grift to help your kid get into Harvard easier (which in many cases it is which is where this is super valid), that's not a great form of privilege. But if private school is a superior education that allows your kid to contribute in a more valuable way to society, then despite the fact that privilege creates privilege, it also creates competence, which should be positive-sum. Then white guilt is actively destructive!",
                "I'd say it's hard to find things that are collectively sacred at the level of Christianity until / if new forms of religion appear, but I think there are things that are more sacred. Elon-esque human expansion across the universe, scientific progress, localism over national / global politics & rebuilding communities, a \"holy war\" against climate change",
                "Sahil Handa:",
                "Oh for sure I agree. Guilt like this about schools can be destructive. Parents are literally denying their kids opportunities because many black people don’t get to have them. The obvious solution is to make the opportunity available to black + white people! racial justice is not necessarily zero sum, but that’s how it’s playing out in the streets and in the pages of the NYT...",
                "^ reply to your first text",
                "I think some of the appeal of racial justice is that it feels sacred",
                "Kush Sharma:",
                "For sure! I do have to run now but this was awesome, had a great time and think we came up with some dope ideas :)",
                "Sahil Handa:",
                "Great talk man"
            };

           
        private static string[] lines2 { get; } =
        {
                "Sahil Handa:",
                "Dude what do you think of contemporary interior design / architecture. Like the aesthetic of all the new coffee shops",
                "Like incandescent lights, white walls, chalkboard menus, maybe plants",
                "Tunc Otzemir:",
                "I think it’s good for the cafes",
                "Sahil Handa:",
                "How so",
                "It’s kind of nice",
                "Comforting",
                "Tunc Otzemir:",
                "It is nice but not super cozy",
                "Sahil Handa:",
                "cold",
                "Tunc Otzemir:",
                "And promotes an atmosphere in which ppl are prompted to leave in a reasomable time",
                "Which is good for then",
                "But i do like the extremely cozy, home like, never leave kinda places",
                "Sahil Handa:",
                "ah",
                "Me too",
                "Tunc Otzemir:",
                "Esp if u wanna work or sit around and chat",
                "this is like emblematic of the focus on productivity",
                "Sahil Handa:",
                "yes",
                "They are almost designed for a quick business meeting",
                "Tunc Otzemir:",
                "like come get your coffee enjoy a beautiful, therapeutic space for half an hour or so",
                "Sahil Handa:",
                "Or a quick phone call",
                "Tunc Otzemir:",
                "And move on to your actual life or whatever gif",
                "Gig u need to do",
                "Yeah",
                "Sahil Handa:",
                "The lights and the greenery give a sort of fake homey vibe",
                "Tunc Otzemir:",
                "Like i think esp the design of the seated spaces are the most important in determining the longetivity of the stay",
                "Sahil Handa:",
                "hm",
                "Tunc Otzemir:",
                "I think not homey but, fake outdoorsy. So you will feel refreshed",
                "Sahil Handa:",
                "ah",
                "Tunc Otzemir:",
                "Cause the cozy places are usually dark and not soul nurturing",
                "They are like libraries and homes mixture",
                "Sahil Handa:",
                "Why isn’t that soul nurturing",
                "Tunc Otzemir:",
                "I mean it is",
                "But if you’re taking a quick break from work to get coffee or whatever",
                "You need a lot of light",
                "To make u feel like you’re in a park or sth",
                "Sahil Handa:",
                "yep",
                "Tunc Otzemir:",
                "This space is gorgeous tho the one u sent",
                "But most of the times it is implemeted badly",
                "Sahil Handa:",
                "Yeah fair",
                "Tunc Otzemir:",
                "Would you say blue bottle has a similar design?",
                "Sahil Handa:",
                "Like the places in the smith center",
                "Tunc Otzemir:",
                "For example I hate that place",
                "I feel like I am in a factory it’s overcrowded, everyone is uncomfortably seated",
                "Sahil Handa:",
                "Looking through the window is like looking into a fishbowl",
                "An auarium",
                "*aquarium",
                "It has lots of wood and light",
                "Super white",
                "You think the seats make people stay for less time",
                "The spaces feel so professional and overly designed it gives the sense that there’s now way they could mess up your order, that nothing could go wrong",
                "Like a fancy hospital",
                "Tunc Otzemir:",
                "Yeah I agree",
                "It is like a high tech factory",
                "Sahil Handa:",
                "Haha",
                "Tunc Otzemir:",
                "I want my order to have the possibility of being messed up",
                "That means there is actual human care and labor that goes into it",
                "Sahil Handa:",
                "Yes",
                "Tunc Otzemir:",
                "And that there exists a possibility that when it is not messed up",
                "It will be provided with care and love rather then precision",
                "Like u know they're also cutting costs on everything in these kinda of places"
            };

        private static string[] lines3 { get; } =
        {
            "Jonah Berger:",
            "https://twitter.com/sahilkapur/status/1332411155701264391?s=10",
            "Kind of crazy!",
            "Noah Redlich:",
            "That is crazy!! ",
            "I’m a bit skeptical of exit polls this year tho ",
            "Sahil Handa:",
            "Surprise! Voters are pragmatically rational!",
            "Noah Redlich:",
            "I feel like they can’t be as accurate because of all the absentee voting ",
            "Sahil Handa:",
            "If the rich weren’t manipulating the media, brainwashing Americans to believe in the American dream, and voting in droves for republicans, the masses would elect a president who would take from the rich and give to the poor",
            "Like Bernie",
            "And it would be awful",
            "Noah Redlich:",
            "Exactly!! ",
            "Sahil Handa:",
            "!",
            "Noah Redlich:",
            "Hahahahaha",
            "Sahil Handa:",
            "Thoughts on student loan debt forgiveness?",
            "Im prima facie against it",
            "Noah Redlich:",
            "I’m for it ",
            "I hate the right wing talking point that it’s a bailout of the rich ",
            "Most people with student debt are working class ",
            "Sahil Handa:",
            "Intersting",
            "Didn’t know that",
            "Jonah Berger:",
            "But they live in cities",
            "Sahil Handa:",
            "Most people also don’t go to college",
            "Jonah Berger:",
            "We need to give money to republicans",
            "Sahil Handa:",
            "yes",
            "Jonah Berger:",
            "Bribe them to vote for us",
            "Sahil Handa:",
            "We can’t just forgive the debt of the educated class, how is that fair to working class people who passed on a 4 year liberal arts degree to hit the job market?",
            "Pragmatically, it would be good for the economy and for our generation",
            "Optics are bad re: culture war",
            "Campbell Erickson:",
            "Lol true",
            "Sahil Handa:",
            "https://twitter.com/PrinceVogel/status/1299886882139058177?s=20",
            "Jonah Berger:",
            "Lol if we only forgave black people’s debt there would be a civil war",
            "Sahil Handa:",
            "Reparations !",
            "The higher education industry has collectively ripped off so many heads",
            "Its just too damn expensive" };
        private static string[] lines4 { get; } =
            {
            "Garrett Walker:",
            "I read a crazy stat that between 250 and 500 million people are going to fall back into poverty as a result of covid",
            "Sahil Handa:",
            "Holy shit",
            "Garrett Walker:",
            "So we definitely need some PH innovation",
            "Sahil Handa:",
            "That’s horrible",
            "Yep",
            "Garrett Walker:",
            "That totally flipped my perspective on the shutdown",
            "Sahil Handa:",
            "Yeah I’m on team free america",
            "Garrett Walker:",
            "That's what the kids like to hear",
            "Sahil Handa:",
            "we got to get back to work",
            "4 days on, 10 days off... or something like that",
            "Garrett Walker:",
            "The problem is marketing it to the left when the optics are just \"You want to kill my grandparents to make money\"",
            "Sahil Handa:",
            "Yep",
            "People don’t see that economic loss=death as well",
            "Garrett Walker:",
            "Great quote from Condorcet (paraphrasing): \"The only difficult question is how to explain complex economic policies to the masses\"",
            "Sahil Handa:",
            "Yep that’s a tough one",
            "Politics is almost 100% about the optics, not actual substance",
            "I think the only solution is to ensure that the people who end up in power are benevolent and educated",
            "Garrett Walker:",
            "This is true",
            "Sahil Handa:",
            "Not sure how that’s possible though...",
            "Garrett Walker:",
            "Yeah. You should read Burke's Speech to the Electors of Bristol",
            "Sahil Handa:",
            "I’ll check it out",
            "I’m kind of sympathetic to him",
            "Garrett Walker:",
            "Dems in particular have gone down this hole of increasing transparency after 1968, when Humphrey won the nomination despite not running in any primaries",
            "So now it's just grassroots without any oversight, leading to bad candidates and populist policies",
            "Anyway. These are the questions we get to address",
            "Sahil Handa:",
            "yep",
            "Democratic Party is no longer a party",
            "They let Bernie run!!",
            "At this point they are just an empty shell",
            "Garrett Walker:",
            "Definitely not helped by the fact that conservative values are broadly reconcilable: imagined 1950s white agrarian culture, laissez-faire economics, hawkish foreign policy, etc.",
            "How the hell do Dems expect to get minority voters, feminists, intellectuals, LGBT activists, and the working class on the same page?",
            "We need a Macron-esque third party",
            "Though probably not possible with current party structures" };
        private static string[] lines5 { get; } =
            { //convo w/ noah, replaced his name w/ sahil's to test inbox code. 
            "Sahil Handa:",
            "The structure of our economy is fucked ",
            "A bunch of unnecessary office jobs getting rich who then support a massive service sector ",
            "Of course if you look at the numbers most trade deals have been net positive ",
            "In terms of jobs ",
            "The disruption though is hard to bear ",
            "When corporations break the law they should go to prison",
            "Noah Redlich:",
            "Yeah I mean they might increase the number of jobs but I think a lot of the jobs end up being lower pay",
            "And the higher paying ones end up on the coasts",
            "Love that!!",
            "Sahil Handa:",
            "Honestly they have too much legal power",
            "If they get to be people they can go to prison!",
            "Noah Redlich:",
            "They do!",
            "But corporations are not people!!",
            "Sahil Handa:",
            "Well in fact they have more legal rights than people do to some extent ",
            "They are collections of people doing something ",
            "The engines of progress ",
            "Noah Redlich:",
            "Yeah they definitely shouldn’t tho",
            "They aren’t entitled to the same treatment by the gov’t as people are",
            "Sahil Handa:",
            "Yes for instance if they go bankrupt we should just take all their owners personal money",
            "Psych ",
            "The whole point of a corporation is a legal shield ",
            "It allows people to take risks ",
            "Noah Redlich:",
            "Hahahaha ",
            "But it shouldn’t be that way",
            "It makes no sense to make corporations get away with behavior that individuals would be penalized for ",
            "Sahil Handa:",
            "Well its just to protect personal assets",
            "Of course it depends case by case",
            "We should think of a corporation as a person feeder . So Xerox corp feeds 27k people, or thereabouts",
            "Noah Redlich:",
            "Yeah but we can’t just allow corporations to engage in behavior that would be blatantly unethical if individuals did it ",
            "Sahil Handa:",
            "By paying wages and getting profit through collective action",
            "Noah Redlich:",
            "But they aren’t jut feeding people? ",
            "Just ",
            "Sahil Handa:",
            "Its just hard to punish corporations in the same way people are",
            "Right now the solution is just make them pay up",
            "But jailing executives would be better",
            "yet. I hold firm that corporations as a concept and in practice are a decent invention. They allow a person to separate certain business actions from the rest of their life. Yet when corporations (or people in them) cross some lines they should face personal consequences",
            "Noah Redlich:",
            "Yeah I agree with all of that",
            "I’m not against corporations inherently",
            "They just can never be above the law" };
        //private static string[] lines6 { get; } =
        //    {
        //    "Jonah Berger:",
        //    "<img src=\"https://i.postimg.cc/Z5bxb1Y1/owl.jpg\" alt=\"owl\"/>",
        //    "<img src=\"https://i.postimg.cc/RC2x6xWJ/rockHike.jpg\" alt=\"rockHike\"/>",
        //    "<img src=\"https://i.postimg.cc/2SZSg5hG/bird-Mid-Flight.jpg\" alt=\"bird-Mid-Flight\"/>",
        //    "<img src=\"https://i.postimg.cc/L8pdDkBH/waterfall.jpg\" alt=\"waterfall\"/>",
        //    "Sahil Handa:",
        //    "<img src=\"https://i.postimg.cc/XqGxShWT/selfie.jpg\" alt=\"selfie\"/>",
        //    "Jonah Berger:",
        //    "<img src='https://i.postimg.cc/J4ttmL9y/bug.jpg' border='0' alt='bug'/>",
        //    "Sahil Handa:",
        //    "<img src=\"https://i.postimg.cc/jd9j8fwC/dog.jpg\" alt=\"dog\"/>",
        //    "<img src=\"https://i.postimg.cc/WbP7KdBp/marsh.jpg\" alt=\"marsh\"/>",
        //    "<img src=\"https://i.postimg.cc/pT2V9Y7c/colorado.jpg\" alt=\"colorado\"/>",
        //    "Jonah Berger:",
        //    "<img src=\"https://i.postimg.cc/fb86MG4L/utahSnow.jpg\" alt=\"utahSnow\"/>",
        //    "<img src=\"https://i.postimg.cc/gkRF3thS/snow-Cliffs.jpg\" alt=\"snow-Cliffs\"/>",
        //    "<img src=\"https://i.postimg.cc/y6LxZt7m/blackbird.jpg\" alt=\"blackbird\"/>",
        //    "Sahil Handa:",
        //    "<img src=\"https://i.postimg.cc/kM2dgggd/sunset.jpg\" alt=\"sunset\"/>",
        //    "Jonah Berger:",
        //    "<img src=\"https://i.postimg.cc/HLKwtn0g/jSunset.png\" alt=\"jSunset\"/>",
        //    "Sahil Handa:",
        //    "<img src=\"https://i.postimg.cc/qR38DrQC/glowing.jpg\" alt=\"glowing\"/>",
        //    "<img src=\"https://i.postimg.cc/Xq1v6GsH/brews.jpg\" alt=\"brews\"/>",
        //    "<img src=\"https://i.postimg.cc/mrh3MCHj/niceTree.jpg\" alt=\"niceTree\"/>",
        //    "<img src=\"https://i.postimg.cc/1z055YWN/dogInBed.jpg\" alt=\"dogInBed\"/>",
        //    "Jonah Berger:",
        //    "<img src=\"https://i.postimg.cc/SsrsVtCp/bird-On-Sign.jpg\" alt=\"bird-On-Sign\"/>",
        //    "<img src=\"https://i.postimg.cc/wT3vc2BS/clouds.jpg\" alt=\"clouds\"/>",
        //    "<img src=\"https://i.postimg.cc/25ksRzKM/snakes.jpg\" alt=\"snakes\"/>",
        //    "Sahil Handa:",
        //    "<img src=\"https://i.postimg.cc/kXFydnCQ/marsh2.jpg\" alt=\"marsh2\"/>",
        //    "Jonah Berger:",
        //    "<img src=\"https://i.postimg.cc/QdfkH0HV/hike.jpg\" alt=\"hike\"/>",
        //    "Sahil Handa:",
        //    "<img src=\"https://i.postimg.cc/RhkdMRVq/Screen-Shot-2020-12-04-at-11-22-08-PM.png\" alt=\"Screen-Shot-2020-12-04-at-11-22-08-PM\"/>",
        //    "send some more later buddy","love the pics"};


        private static string user = "Sahil Handa";

        static LoadDms()
        {
            InboxList.Add(new PrivateMessage(lines0, user));
            InboxList.Add(new PrivateMessage(lines1, user));
            InboxList.Add(new PrivateMessage(lines2, user));
            InboxList.Add(new PrivateMessage(lines3, user));
            InboxList.Add(new PrivateMessage(lines4, user));
            InboxList.Add(new PrivateMessage(lines5, user));
            //InboxList.Add(new PrivateMessage(lines6, user));
        }
        

        public static PrivateMessage GetPm(List<User> users)
        {
            foreach (var convo in InboxList)
            {
                if (convo.HasSameUsers(users))
                {
                    return convo;
                    Console.WriteLine("found matching conversation ");
                }
            }
            return null;
        }
    }
}
