using System;
using System.Collections.Generic;
using System.Reflection.Metadata.Ecma335;

namespace uiExp.Client
{
    public class LoadConvos
    {
        public static List<string[]> linesList = new List<string[]>();
        private static string[] lines1 { get; } =
            {
                "Marshall Sloan:",
                "Majoritarian politics commanding the morals is what trump is about rejecting",
                "It’s a righteous mission if he weren’t a racist buffoon ",
                "Eli Burnes:",
                "hmmm",
                "Marshall Sloan:",
                "The tea party is just tired of majoritarian tyranny ",
                "I’ve been saying this for a while",
                "Eli Burnes:",
                "Who is the majority",
                "Marshall Sloan:",
                "The woke",
                "Who command industry and schools",
                "Eli Burnes:",
                "But the woke are a minority",
                "Marshall Sloan:",
                "And government ",
                "Eli Burnes:",
                "With power",
                "Marshall Sloan:",
                "But they are a majority of noise",
                "Eli Burnes:",
                "true",
                "That’s the irony",
                "Marshall Sloan:",
                "They command press, schools, and industry ",
                "We live in a society governed by majoritarian tyranny of the woke",
                "It troubles me often",
                "Eli Burnes:",
                "hah",
                "Insane how ever corporation made a statement on BLM",
                "Marshall Sloan:",
                "Yup",
                "Eli Burnes:",
                "Radical politics is establishment politics",
                "Marshall Sloan:",
                "Yes and no",
                "Eli Burnes:",
                "Status quo",
                "Marshall Sloan:",
                "It’s not radical it’s very tame ",
                "Eli Burnes:",
                "That’s the point",
                "*my point",
                "Marshall Sloan:",
                "French Revolution, libya, Egypt, China",
                "Those were radical ",
                "Ours is so tame",
                "Marching, rioting ",
                "Isn’t wild",
                "It’s childish",
                "Eli Burnes:",
                "yep",
                "Marshall Sloan:",
                "There is no radical reforming of ideas",
                "No robust idea on a reformulation of society besides vomiting up washed up socialist speak that has never worked",
                "Eli Burnes:",
                "Isn’t that the history of antiracism though, like blacks just want to be treated like whites",
                "Marshall Sloan:",
                "But they are",
                "By and large",
                "Eli Burnes:",
                "So it doesn’t require radical rethinking to suceed",
                "That’s fiar",
                "But discrepancies are still absurd wrt poverty, incarceration, crime etc.",
                "Police are a straw man in all of this perhaps",
                "A scapegoat",
                "Marshall Sloan:",
                "That’s the issue. Our majoritarian politics validates their stance, but nothing changes. Wealth and class don’t change. Their criminality doesn’t change. So they’re just overwhelmed by this lethargic creep towards our countries eventual realization that nothing can be done besides their effort to fall into American conformism until they flourish too. ",
                "I wonder when that day will come.",
                "Marshall Sloan:",
                "Because, the feature left out is that in order to be treated as a white you in fact need to act like oneZ",
                "That may sound heinous ",
                "But it’s the functioning of American societt",
                "Eli Burnes:",
                "Hm that makes sense interesting interpretation, so success in america requires conformism on your view",
                "Marshall Sloan:",
                "Entirely",
                "It’s how we operate",
                "Eli Burnes:",
                "Asian Americans, are they conformist?",
                "Marshall Sloan:",
                "We are a conformist society",
                "Yes",
                "Entirely",
                "Eli Burnes:",
                "But they do it to an extreme",
                "Marshall Sloan:",
                "But it’s conformism to an idea. That’s why there is such anxiety between immigrants and natives, right? If each immigrant class strives to do better, then the prior class will stagnate and be left behind - fueling this cycle of anxiety.",
                "Eli Burnes:",
                "Hm",
                "Marshall Sloan:",
                "Blacks got the worst of the stick. They - like many whites - are left behind. But they didn’t have the class and wealth to still rise up.",
                "Like some WASPS are still rich. It isn’t just more recent immigrants",
                "Because class is still currency here.",
                "Eli Burnes:",
                "true.",
                "Wasp society is decadent though",
                "Dying and fracturing",
                "Marshall Sloan:",
                "I suppose",
                "We live in a society where clout govern",
                "And without their clout they’re imploding and resorting to normal means of achieving clout",
                "Which is flashing money",
                "Eli Burnes:",
                "haha",
                "The culture of the nouveau riche is taking over. Because “class” as a state of mind and manners is less and less respected",
                "Simpler and more vulgar ways are being used to assert dominance and prestige",
                "Marshall Sloan:",
                "Yes"
            };



            private static string[] lines2 { get; } =
            {
                "Eli Burnes:",
                "\"They stalk about in our midst as living reproaches, as warnings to us—as though health, fitness, strength, pride, the sensation of power, were really vicious things in themselves, for which one would have some day to do penance, bitter penance. Oh, how they themselves are ready in their hearts to exact penance, how they thirst after being hangmen! (GM III 14)\"",
                "Here Nietzsche describes the revolt of the lowly, the oppressed, against the strong",
                "He thinks the less powerful have succeed by making the powerful guilty – guilty for their power",
                "The psychological trick of of the oppressed, on Nietzsche’s view, is to make the attributes of the powerful seem ridiculous, cause for guilt",
                "Can we compare this to modern notions of privilege?",
                "Kush Sharma:",
                "Creating guilt among the powerful functions in a fractal way. The aristocrats of the Roman republic had the same internal dynamics - e.g. Gaius Marius, a low-born but extremely competent military general who denounced the high aristocracy of his day for responding to crises with haughty arrogance that didn't correspond to their abilities. They had power, but competence isn't hereditary like power is/was, so the critiques hit on a legitimate point.",
                "Eli Burnes:",
                "What do you mean by fractal?",
                "Kush Sharma:",
                "Just like the bottom of the bottom (e.g. Jesus and the Jews) were able to critique one level up - establishment Jewish rabbis + the Roman administrators, the same dynamics were occurring within the highest reaches (and maybe occur in every local class / power conflict?)",
                "Eli Burnes:",
                "Hmm interesting",
                "Kush Sharma:",
                "Interesting comparison to upper middle class vs global elite, white lower class vs black / brown underclass?",
                "Elites seem to be failing - globalization didn't live up to its promises, at least for those who already lived in wealthy Western countries. Technology is stagnating. There are legit critiques of competence, but maybe easier to dress those critiques up in moral terms - BLM, privilege, wokeness?",
                "Eli Burnes:",
                "Yeah. To your last text–people see themselves in the context of their local hierarchies. for everyone, there’s always a more powerful group and a less powerful group. There’s research that suggests people compare their incomes to those around them. to someone in the upper middle class the excessive wealth of the elite elite might invoke jealousy + condemnation.",
                "Moral/psychological memes are perhaps the most effective way for the powerless to gain power/challenge those in power. Nietzsche totally understands this",
                "Kush Sharma:",
                "Ahhh yes, and that means that whoever is one level up in the apparent hierarchy becomes the",
                "*oops more to come",
                "\"enemy\" and all levels above that are illegible to the person at a particular local level. One explanation for why the Trump demo's anger has been aimed at those one below (illegal immigrants, POC lower / under class) and one above (liberal academics, professional / managerial class); and that anger was leveraged by right elites.",
                "Does the dominance of a moral / psych meme imply that it is more truthful or moral? Or does it just imply greater memetic fitness?",
                "Eli Burnes:",
                "Ohh interesting take on trump. Certainly true that his anti elite rhetoric does not target the rich + most powerful in the way that Warren’s did in her primary campaign. she has a different audience",
                "The wokeism meme (which is quite complex, of course) may not be that fit–it might just fizzle out. But by definition it’s been super high fitness up to this point",
                "Don’t think dominance implies truth",
                "But it does suggest that it fit’s nicely into previously established belief systems/memeplexes",
                "For instance wokeism thrives on the generally accepted idea (in Western European liberalism) that equality is the most important moral standard/ideal",
                "And the basic equality of humans the fundamental moral fact",
                "Moral/psych memes have to seem true, at least",
                "my view is that morality is socially constructed (to some extent) so being dominant means participating in constructing morality at least",
                "Kush Sharma:",
                "Yep! The fitness of wokeism is super interesting - my take is that it's not fit, because it misunderstood the basic nature of power in a capitalist system. Power in the US doesn't come from political activism, protests, or governmental bodies; all the areas where wokeness has gained some power. All those are subservient to capital or irrelevant int he face of capital - see wokeism being coopted by F500s and rejected by entrepreneurs. Ofc future forecasts are always hand wavy though :)",
                "Ya, and it hit trouble when it contradicted another deeply held moral fact - freedom of speech and expression (esp in the US)",
                "Being a part of the dominant morality gives you cultural capital - interesting dynamics occur when (mainstream) cultural capital is less and less valuable",
                "Eli Burnes:",
                "Yes wokeism seems to me to be not that effective in terms of real political gains for black people–massive investment in poor, black, urban areas, for instance, is badly needed but nowhere in sight. We’ll see if the police reforms we get are actually effective and fair or are not...",
                "Freedom of speech and expression might not be the biggest roadblock to wokeism– it runs up against humanism, to some extent we should see people first as human beings and only second as people of a certain race. It also feels christian. There’s heresy, apostates, original sin (slavery). Not sure if this is good for fitness or not–we live in a secular culture but puritanism is still quite dominant. Any resistance movement meets backlash, gains for black people in the US seem always to be met with pushback from whites. Maybe wokeism will succeed because it changes what type of push back is acceptable. wokeism undermines the foundation of white power by making white people question their privilege–often to an insane degree. ",
                "Kush Sharma:",
                "Yeah! It's post-Christianity Christianity, but without Salvation! It fills ~80% of the gap Christianity left in the culture, but without offering metaphysics or \"ultimate\" morality - it only offers relative, \"profane\" social morality. It's redistributionist rather than growth-oriented.",
                "Yep I think that's fair and it will succeed in making gains for black people, but at the expense of cultural progress as a whole. MLK-style civil rights didn't have this drawback, and even Malcolm X-style secession didn't as much - one focused on unity, not guilt, and the other focused on internal strength and exit, not voice",
                "Difficult to say if progress (for black people) is possible without the guilt though - a huge part of the guilt is baked into the social reality of the last 200y, and needs to be confronted and processed by the culture",
                "Eli Burnes:",
                "good point on salvation. By definition, psychological purification from white supremacy (a sort of salvation or redemption) is not possible. And the apparent goal of the present racial justice movement–exact equity in all social outcomes between whites and blacks–is frankly not possible, unless we get to a world in which race matters not at all. There seems to be no endpoint.",
                "I think white guilt might actually be doing some effective things",
                "Kush Sharma:",
                "Yep - maybe then the question is one of attention allocation between different causes? Social / racial justice is needed, but with 10 other causes that are equally if not more pressing (stagnation, climate change, ex-risk, etc) allocating all our cultural attention to a cause that's inherently zero-sum and profane rather than positive-sum and sacred seems dangerous",
                "Eli Burnes:",
                "Here’s an example. I think that education is the most effective way for wealthy white people to maintain their family’s power–paying for private school may be more effective than a trust fund. Insofar as this is true, wokeism might be working, because it undermines the idea that white people should be able to use money to get better education. Woke white parents are getting uncomfortable maintaining their family’s privilege–their guilt might lead to material and psychological solidarity with non white people.",
                "For sure, attention allocation this summer shifted almost entirely (at least in white managerial class) to racial justice, evidenced by NYT bestsellers. Not sure racial justice get’s too much attention, of course it often hasn’t gotten enough.  But perhaps it wasn’t a good use of attention in the summer leading up to the election.",
                "What can we pay attention to that’s sacred?",
                "Kush Sharma:",
                "Isn't non-zero sum privilege desirable though? If private school is just a grift to help your kid get into Harvard easier (which in many cases it is which is where this is super valid), that's not a great form of privilege. But if private school is a superior education that allows your kid to contribute in a more valuable way to society, then despite the fact that privilege creates privilege, it also creates competence, which should be positive-sum. Then white guilt is actively destructive!",
                "I'd say it's hard to find things that are collectively sacred at the level of Christianity until / if new forms of religion appear, but I think there are things that are more sacred. Elon-esque human expansion across the universe, scientific progress, localism over national / global politics & rebuilding communities, a \"holy war\" against climate change",
                "Eli Burnes:",
                "Oh for sure I agree. Guilt like this about schools can be destructive. Parents are literally denying their kids opportunities because many black people don’t get to have them. The obvious solution is to make the opportunity available to black + white people! racial justice is not necessarily zero sum, but that’s how it’s playing out in the streets and in the pages of the NYT...",
                "^ reply to your first text",
                "I think some of the appeal of racial justice is that it feels sacred",
                "Kush Sharma:",
                "For sure! I do have to run now but this was awesome, had a great time and think we came up with some dope ideas :)",
                "Eli Burnes:",
                "Great talk man"
            };

            private static string[] lines3 { get; } =
            {
                "Caleb Rhodes:",
                "Ok, so today we will be talking about the Philip Guston Retrospective Controversy",
                "Ethan do you want to set the scene",
                "Ethan Fields:",
                "Happy to! So the current controversy around Philip Guston’s work boils down to the fact that a retrospective of his was delayed over the summer as a result of the death of George Floyd and the ensuing protest for racial justice in the US",
                "This was supposed to be a show that spanned a couple of museums in the US and UK, specifically the Houston MFA, Boston MFA, National Gallery of Art, and Tate Modern",
                "Caleb Rhodes:",
                "Yes, the national gallery of art and the 4 partner museums have since rescheduled initially for 2024 and now to 2022. The reason for the delay was because of KKK imagery in Guston’s (a white Jewish man’s) art that the curators claim wasn’t contextualized enough",
                "Ethan Fields:",
                "But it was pushed back to 2024 until recently when it was placed in between at 2022",
                "Great minds think alike!",
                "Caleb Rhodes:",
                "Interestingly, the move has been largely panned across the board by a diverse and well-known crowd of artists and cultural commentators",
                "I guess the first question Ethan is whether you agree that the show should have been postponed?",
                "Ethan Fields:",
                "That’s certainly the million dollar question, and I think one needs to start by examining the intentions of the Museum Board of directors who really pushed the decision.",
                "Caleb Rhodes:",
                "Fair enough",
                "Ethan Fields:",
                "Even prior to the pandemic, the art and museum world was in a state of flux as institutions were critiqued for accepting dubious donations",
                "So the board members clearly wanted to mitigate any sense of controversy that could have exposed them to public dissatisfaction",
                "Caleb Rhodes:",
                "Yeah this is definitely a defensive move, but was it motivated by money or just fear of outrage?",
                "Ethan Fields:",
                "I know that a lot of people found the decision patronizing, and I personally believe that adopts a rather “snowflake” view of the public",
                "Caleb Rhodes:",
                "Absolutely, and from what I’ve read, the exhibition catalogue does a good job of contextualizing these images already",
                "Ethan Fields:",
                "In response to your second question: I’ve been fortunate enough to get some exposure to the Ford Foundation the past several months through my time at the Museum of Chinese in America",
                "And Darren Walker, the head of the foundation, was one of the voices advocating for the postponement",
                "The Ford Foundation is actually a really fantastic source of funding for cultural institutions across the country",
                "And they recently rolled out a generous donation of over $200 million to a variety of small to mid sized institutions across the US to help them survive Covid",
                "Caleb Rhodes:",
                "Interesting! It just seems to me that at a moment of “cultural reckoning,” cultural institutions and their benefactors  should not be shying away from tough conversations but leaning into them",
                "Ethan Fields:",
                "These institutions mostly being cultural museums representing specific ethnic or immigrant stories like MOCA",
                "I completely agree!",
                "This is just to say that I think that some of their intentions likely stemmed from a good place",
                "Caleb Rhodes:",
                "And I believe everyone’s intentions here are good",
                "Ethan Fields:",
                "As cultural institutions, I think museums have a responsibility to shape the public’s sense of morality and tell honest stories",
                "Those stories aren’t always easy",
                "And they can be quite uncomfortable at times",
                "But confronting them is certainly the only way to move forward",
                "Caleb Rhodes:",
                "Yes and I find it disappointing that these museums think they are doing a service by stalling a conversation",
                "Frankly it seems more about them than about the public or the story",
                "Ironically perhaps they are the ones who aren’t ready for a real conversation",
                "Ethan Fields:",
                "Yes they certainly seem scared of rocking the boat in any manner",
                "Caleb Rhodes:",
                "Truly peak self-censorship",
                "Ethan Fields:",
                "But it’s part of the climate given the Warren Kanders debacle at the Whitney",
                "You’re certainly right, and this seems like a big issue these days",
                "People are really scared of overstepping in any way because they’re scared of being cancelled or labeled something negative",
                "And while I certainly believe that hate speech and racism deserves to be curtailed and rooted out, I do think that people make mistakes",
                "And they can make them in good faith",
                "But if we don’t allow people to make mistakes",
                "Then they will never grow from them",
                "And that will just breed another cultural disaster",
                "Caleb Rhodes:",
                "Absolutely! I think we’re stumbling on another convo here. But definitely this controversy is revealing the extent to which our discourse on race is paralyzed by fear of being perceived wrongly",
                "But thanks Ethan, always great to talk! 😘",
                "Ethan Fields:",
                "Yes, that topic deserves a book not a text exchange for sure",
                "Always happy to chat!"
            };

            private static string[] lines4 { get; } =
            {
                "Ian Liefer:",
                "Why do you think Biden is gonna win?",
                "He has unprecedented black and Latino support",
                "And hasn’t lost any of his base",
                "Henry Burnes:",
                "Not true elderly people and suburban women are going for Biden, two critical demographics for Trump",
                "*latino male support",
                "Ian Liefer:",
                "True but it’s unclear if the data supports that in key swing states",
                "Trumps elderly turnout has been strong in Florida",
                "And he has huge Latino support in Arizona and Nevada",
                "Henry Burnes:",
                "Trump can win Florida",
                "As long as Biden wins PA",
                "Ian Liefer:",
                "PA +2 today",
                "Trump",
                "And he registered 80,000 Amish",
                "Henry Burnes:",
                "Wrong",
                "Ian Liefer:",
                "90% pro trump",
                "Henry Burnes:",
                "Wow",
                "Hadn’t heard about that",
                "Might be hard to get to the polls in buggies",
                "Ian Liefer:",
                "True",
                "Henry Burnes:",
                "Trump has no campaign message",
                "Has no idea how to run against Biden",
                "Ian Liefer:",
                "It’s called MAGA bro",
                "Henry Burnes:",
                "He’s getting separate",
                "Ian Liefer:",
                "Lol",
                "I agree",
                "Henry Burnes:",
                "MAGA doesn’t work after you’ve been president for a term",
                "Ian Liefer:",
                "How should he be running then",
                "Henry Burnes:",
                "Pivot on COVID and accept responsibility",
                "Push through a stimulus",
                "Ian Liefer:",
                "Unrelated but I know a kid working in DC for chief economist and he’s a democrat so he’s not biased and he said the democrats won’t accept one before the election",
                "Just strategically",
                "Henry Burnes:",
                "Maybe. But they passed one in the house",
                "Ian Liefer:",
                "True",
                "I agree lol",
                "Henry Burnes:",
                "So does the country descend into chaos if trump wins ?",
                "Ian Liefer:",
                "I’m just disagreeing with everything",
                "I think so",
                "Yeah",
                "Honestly there will prob be conflict either way",
                "Henry Burnes:",
                "Let’s buy some guns then",
                "Ian Liefer:",
                "Agreed",
                "It’s funny how everyone just thinks their party will win"

            };

        static LoadConvos()
        {
            linesList.Add(lines1);
            linesList.Add(lines2);
            linesList.Add(lines3);
            linesList.Add(lines4);
        }
    }
}
